### ISSUE TITLE
New width, height, x, w properties override form fields and page/module attributes.

### ISSUE THREAD

**Issue by geb-bot** [geb/issues#109]
Originally created by Kevin Richards.

If you have a form, module or page which contains the attributes width, height, x, y then they are broken in the 0.6.0 release.

An example would be a domain object for an Image with attributes url, width, height.

form.width now returns the width of the form NOT the value of the input field.

Similar problems for x,y,height exist.

I'd suggest that these shortcuts are only honoured IF there are no page/module/field attributes which match.

**Comment by erdi** [comment]
A `InvalidPageContent` exception is now thrown now when a content name that conflicts with any of these properties is used.
