### ISSUE TITLE
Setting the value of a select element if an onChange event causes the page to reload will throw an exception

### ISSUE THREAD

**Issue by geb-bot** [geb/issues#155]
Originally created by Ellery Crane.

If you have javascript onChange event handlers on a select element that change the window.location, using Geb to set the value of the select will throw a org.openqa.selenium.StaleElementReferenceException. Example:

<select name="artist" onChange="window.location='http://www.google.com';">
    <option value="1">Ima Robot</option>
    <option value="2">Edward Sharpe and the Magnetic Zeros</option>
    <option value="3">Alexander</option>
</select>

Then, in the test:

when:
  $("form").artist = 3
then:
  thrown(org.openqa.selenium.StaleElementReferenceException)

**Comment by erdi** [comment]
Happens for radio buttons as well.

**Comment by erdi** [comment]
According to this [mailing list thread](https://groups.google.com/d/msgid/geb-user/e5955541-23c4-44cf-8181-473159cffb65%40googlegroups.com?utm_medium=email&utm_source=footer) it might also occur for regular text inputs.
