### ISSUE TITLE
Allow per environment driver caching

### ISSUE THREAD

**Issue by geb-bot** [geb/issues#164]
Originally created by Tomas Lin.

Currently, Geb caches the first driver created and reuses this for all tests. 

For some scenarios ( i.e, testing mobile views alongside main views ), it would be helpful to have a mechanism that allows for more than one driver to be cached and provide a mechanism for tests to switch to a different cached driver.

For example, one might want to run all their tests in the default environment, but when testing mobile views, be able to switch to mobile via something like switchEnvironment( 'mobile' ) or switchEnvironment( 'android' ).

**Comment by erdi** [comment]
You should use your build system capabilities to support this requirement. When using Gradle for example you could separate your mobile view tests from your main view tests using JUnit categories and have different test tasks run different test categories in different environments.
