### ISSUE TITLE
Use native WebDriver way of handling alerts

### ISSUE THREAD

**Issue by geb-bot** [geb/issues#243]
Originally created by Marcin Erdmann.

This would greatly simplify the code in `AlertAndConfirmSupport` as well as would allow to avoid issues in situations where page is reloaded after an alert/confirm has been dismissed and where you cannot access the alert/confirm message.

**Comment by erdi** [comment]
This has been reverted and reopened because some drivers seem to not implement the native way of handling alerts correctly or their implementation is not fully stable.

**Comment by erdi** [comment]
Given the incompatibilities between browsers in native alerts handling I think it's better to keep the compatibility layer Geb provides for the price of not being able to access the alert/confirm message when page is reloaded after an alert/confirm has been dismissed.
