### ISSUE TITLE
Add pause() method to hold the browser open.

### ISSUE THREAD

**Issue by geb-bot** [geb/issues#247]
Originally created by Luke Daley.

Similar to pause() in AngularJS's scenario runner.

See: http://markmail.org/search/?q=list%3Aorg.codehaus.geb.user#query:list%3Aorg.codehaus.geb.user+page:1+mid:cfam366iwzayostu+state:results

**Comment by bullshit** [comment]
+1

**Comment by jeremyjjbrown** [comment]
This is sort of a no brainier right? Debugging Selectors in a dynamic webapp is really painful.

**Comment by erdi** [comment]
This is currently not of the highest priority as you can achieve pretty much the same outcome using breakpoints in an IDE but contributions are always welcome.
