### ISSUE TITLE
Ie 11 : << or sendKeys() is NOT supporting for file Upload operation

### ISSUE THREAD

**Issue by kasthurk** [geb/issues#378]
I am using geb, spock, groovy for my framework

File upload is achieved in our application using below code. ( For Chrome and Firefox )
Locator << file_path

Above code is not working for IE 11.

**Comment by erdi** [comment]
Geb delegates sending keys to WebDriver so it's a WebDriver issue. Looks like a [similar issue](https://code.google.com/p/selenium/issues/detail?id=3858) has already been filed in WebDriver bug tracker.
