### ISSUE TITLE
Browserstack tunnel opened without -forcelocal option

### ISSUE THREAD

**Issue by matankatz** [geb/issues#379]
Hi,

When launching the tunnel executable of browser stack, it is launched without -forcelocal, which is required to access local servers via the executing host.

Here is a reference for this option:
https://www.browserstack.com/local-testing#whitelist-ip

The local capability doesn't affect in this case.
Please add to assembleCommandLine() in BrowserStackTunnel.groovy the option to launch it with -forcelocal:

final protected boolean isForceLocal

BrowserStackTunnel(Project project, Logger logger, BrowserStackAccount account, List<URL> applicationUrls, boolean isForceLocal = true) {
        super(project, logger)
        this.account = account
        this.applicationUrls = applicationUrls
        this.isForceLocal = isForceLocal
    }

@Override
    List<String> assembleCommandLine() {
        def tunnelPath = project.fileTree(project.tasks.unzipBrowserStackTunnel.outputs.files.singleFile).singleFile.absolutePath
        def commandLine = [tunnelPath]
        commandLine << account.accessKey
        if (account.localId) {
            commandLine << '-localIdentifier' << account.localId
        }
        if (applicationUrls) {
            commandLine << "-only" << assembleAppSpecifier(applicationUrls)
        }
        if (isForceLocal) {
            commandLine << "-forcelocal"
        }
        commandLine
    }

Thanks,
Matan

**Comment by erdi** [comment]
There is a PR available for this: https://github.com/geb/geb/pull/99.

**Comment by erdi** [comment]
Superseded by #385.
