### ISSUE TITLE
text does not work on header elements with HtmlUnitDriver 2.16

### ISSUE THREAD

**Issue by chrylis** [geb/issues#380]
With HtmlUnitDriver, I have this HTML in my page:

    <div class="sidebar-section">
        <h3 class="hidden-xs">Digitizer Portal</h3>
        <li>
            <a href="/digitizer/clients">
                <i class="fa fa-users" />
                <span class="nav-label"> Clients</span>
            </a>
        </li>
    </div>

I can select this div (and its siblings) with the top-level find `$('div.sidebar-section')`; this correctly returns a navigator with a list of all of the matching divs. Additionally, I can execute the find `sections.$('h3')`, which returns all of the `h3` elements inside these sections, whose `toString()` is `<h3 class="hidden-xs">`.

However, the text methods on these elements consistently returns empty; `headers*.text()` returns an array of empty strings, and attempting to use the `text` in a finder or filter always returns no results.

I've confirmed in the Eclipse inspector that the immediate child of the `h3` elements is a `DomText` with the appropriate `data_` (the expected text).

**Comment by erdi** [comment]
I'm assuming that given your `h3` element has a class called `hidden-xs` it is not vissible. Geb is using `WebElement.getText()` to implement `Navigator.text()` and [the javadoc for `WebElement.getText()` states that it only returns visible text](http://selenium.googlecode.com/git/docs/api/java/index.html). You will need to either make the element visible or execute some [javascript](http://www.gebish.org/manual/current/javascript.html#executing_arbitrary_code) to get its text.

**Comment by chrylis** [comment]
Sorry, I apparently missed the notification on this one.

I'm explicitly setting calling `driver.manage().window().size =` to ensure that the viewport is big enough (1280px wide) that the text is visible. Does this suggest there's a bug in HtmlUnit?

**Comment by erdi** [comment]
Hidden here does not mean that it's not in the viewport - it means that it's hidden using css hence I mentioned the `hidden-xs` class in my previous comment.

**Comment by chrylis** [comment]
The Bootstrap `hidden-xs` class is a media query for a very small viewport. Anything over 767px displays the text.
