### ISSUE TITLE
Wrong gradle task to build javadoc for api in readme page.

### ISSUE THREAD

**Issue by levsa** [geb/issues#387]
The readme page says `./gradlew :doc:manual:compileApi`for building the api reference, but that didn't work. I could find the task `apiDoc` though.

**Comment by erdi** [comment]
Thanks for reporting. 

The `readme.md` file needs some restructuring and the plan is to pull out a `contributing.md` file out of it that will contain information related to contributing. The issue you've found will be addressed when that happens.

**Comment by levsa** [comment]
Great, thanks! Is there any plans to host the javadoc online somewhere?

**Comment by erdi** [comment]
It's hosted on gebish.org, under API in the top menu.

**Comment by levsa** [comment]
Great thanks! I need to improve my googling skills apparently.
