### ISSUE TITLE
Include documentation on how to run with PhantomJS

### ISSUE THREAD

**Issue by boekhold** [geb/issues#396]
Just throwing this here, as I'm not subscribed to the mailing lists. I couldn't find any outright information on how to use geb with the PhantomJSDriver inside a script, and it took some googling and fiddling to make this work. It's probably useful information for other people:

1. Download PhantomJS 2.0.0
2. Enable in your groovy script as:

```groovy
@Grapes([
    @Grab("org.gebish:geb-core:0.12.1"),
    @Grab("org.seleniumhq.selenium:selenium-java:2.45.0"),
    @Grab(group='com.codeborne', module='phantomjsdriver', version='1.2.1', transitive='false')
])
import geb.Browser
import org.openqa.selenium.phantomjs.PhantomJSDriver
import org.openqa.selenium.phantomjs.PhantomJSDriverService
import org.openqa.selenium.remote.DesiredCapabilities
import org.openqa.selenium.Dimension

// Set up PhantomJS driver, a headless web browser,
// much faster than using the Firefox driver!
def caps = new DesiredCapabilities()
caps.setCapability(
    PhantomJSDriverService.PHANTOMJS_EXECUTABLE_PATH_PROPERTY,
    "C:/Maarten/local/phantomjs-2.0.0-windows/bin/phantomjs.exe")
def driver = new PhantomJSDriver(caps)
driver.manage().window().setSize(new Dimension(1024, 768))

def browser = new Browser(driver: driver)
```

3. Update the path to where you unzipped the PhantomJS distribution.

Perhaps something that can be included on the web site or in the manual?

Note that at the moment you need to use an unofficial release of the PhantomJS driver due to https://code.google.com/p/selenium/issues/detail?id=8088.

**Comment by erdi** [comment]
I don't intend to maintain a list of configuration steps for all possible drivers. In my view, this kind of information should live in driver documentation and not the Book of Geb. We don't include this information for `InternetExplorerDriver` nor `ChromeDriver` and I see no reason why we should have it for Ghost Driver, especially given that the project [seems to be dormant](https://github.com/detro/ghostdriver#help-needed).
