### ISSUE TITLE
Add asset-pipeline to the site

### ISSUE THREAD

**Issue by erdi** [geb/issues#408]

**Comment by JacobAae** [comment]
I've tried implementing this here: https://github.com/JacobAae/geb-1/tree/asset-pipeline
and it works fine when running locally. However it seems like the assets are not included in the distributions, when running assemble.

Anyone have insights to this?

**Comment by antony** [comment]
Since the build is handled partially by gulp now (via semantic), and the next round of website changes will probably introduce a single bundle built by webpack / rollup, we probably don't need asset-pipeline any more?

**Comment by erdi** [comment]
The idea behind using asset-pipeline was to minify and add hash signatures to asset file names and then serve them with indefinite cache time. If you are able to achieve that with some other tools then we definitely will not need asset-pipeline. :)

**Comment by antony** [comment]
Yep this is basically what webpack / rollup is for - it will also allow us to get rid of the gulp task from the project which is an advantage - no wrapping build tools with build tools.

**Comment by erdi** [comment]
No capacity to work on this, closing as it's more trouble than it's worth.
