### ISSUE TITLE
Manual and API list options are not displayed completely ,when navigated to jQuery-like API page

### ISSUE THREAD

**Issue by Vinodkomeershetty** [geb/issues#414]
![geb1](https://cloud.githubusercontent.com/assets/7869073/10695587/0889a316-79c2-11e5-9e3e-555557cc4702.png)

**Comment by erdi** [comment]
Fixed in https://github.com/geb/geb/commit/c6f04a5bab5bb98a2238571538a4fd599fd0d4e2
