### ISSUE TITLE
http://www.gebish.org/manual wrong file upload example

### ISSUE THREAD

**Issue by maburo** [geb/issues#420]
There is a line with example code:
`$("form").csvFile = uploadedFile.absolutePath`

should be 
`$("form").csvFile.value uploadedFile.absolutePath`

**Comment by erdi** [comment]
No, that snippet is correct. We make sure that our snippets are correct by pulling them out of tests, and the one you mention is tested [here](https://github.com/geb/geb/blob/bd9042457476e8d90ab0d2433a194e783695769c/doc/manual-snippets/src/test/groovy/navigator/FileUploadSpec.groovy#L69).

If you are wondering why it works without having to use the `value()` method then read about [form control shortcuts](http://www.gebish.org/manual/current/#form-control-shortcuts) in the manual.
