### ISSUE TITLE
Failure Scenario - Screen Shot

### ISSUE THREAD

**Issue by vignesh02** [geb/issues#427]
Hi Team,

Currently using Geb testing taking screenshot for all the scenario(passed and failed) and trying to take the screen shot for failure but its not working.

Geb Version - 0.10.0

http://tomaszdziurko.pl/2013/05/taking-screenshot-in-failing-ui-tests-using-geb/

Also tried by adding below line the gebconfig.groovy but its not working.

reportOnTestFailureOnly = true

Can you please share working example code to make it work.

**Comment by erdi** [comment]
This is a usage question and not an issue. Please don't create issues for usage questions especially if you submitted your question to the mailing list. I've responded to [your question on the mailing list](https://groups.google.com/forum/#!topic/geb-user/m0oufd2UG7Y).
