### ISSUE TITLE
Handle iFrame in Chrome Driver using Geb/Groovy

### ISSUE THREAD

**Issue by amiablekrishna** [geb/issues#430]
I am Automate our internal application in Chrome browser using Geb/Groovy, Our Latest version, all future comes under iFrame. So our existing Script cannot able to click any of the element under iFrame.
I used Geb & Selenium Syntax to handle the iFrame, 
withFrame(Index) and (string), 
driver.switchto.frame() also tried.
 I could not able to click the element.
Because of this, i could not able to move forward. Could you please help to find the solution.

**Comment by erdi** [comment]
Please don't create issues with usage questions and use the user mailing list at https://groups.google.com/forum/#!forum/geb-user instead.
