### ISSUE TITLE
Problem with code from manual section "Using modules for repeating content"

### ISSUE THREAD

**Issue by sallaby** [geb/issues#431]
I've been looking into using modules to ease the handling of tables with my project, however there seems to be a problem with the following code from the manual:

>        cell { $("td", it) }
>        productName { cell(0).text() }
>        quantity { cell(1).text().toInteger() }
>        price { cell(2).text().toBigDecimal() }

`$("td", it)`  produces the error: `'$' in 'geb.Module' cannot be applied to '(java.lang.String, ?)'`

Am I missing something or is there a problem here?

**Comment by erdi** [comment]
The snippet in question is pulled in from a [test which exercises that content definition](https://github.com/geb/geb/blob/master/doc/manual-snippets/src/test/groovy/modules/RepeatingContentSpec.groovy#L22) therefore I'm pretty sure that it works.

Can you please share what is the exact invocation of these content definition that is causing your issue? Also, the `?` in `'$' in 'geb.Module' cannot be applied to '(java.lang.String, ?)'` looks suspicious to me - did you remove the reported type before pasting in this error line?

Given that this is most probably a usage question I'm going to close this issue. Please start a thread on [the Geb user mailing list](https://groups.google.com/forum/#!forum/geb-user) if you need more assistance with this.
