### ISSUE TITLE
[GebReportingSpec] Do not try to write report if browser == null or invalid

### ISSUE THREAD

**Issue by kriegaex** [geb/issues#432]
If `browser` is null or otherwise invalid, trying to create a report in [GebReportingSpec](https://github.com/geb/geb/blob/master/module/geb-spock/src/main/groovy/geb/spock/GebReportingSpec.groovy#L44) via `browser.report()` (equivalent to `getBrowser().report()` will automatically create a new broswer instance because this is what [getBrowser](https://github.com/geb/geb/blob/master/module/geb-spock/src/main/groovy/geb/spock/GebSpec.groovy#L41) does if the instance equals null.

Firstly, it does not make sense to create a new browser with an empty window just so as to produce a meaningless screenshot of an empty page.

Secondly, this can be slow and costly for cloud services such as TestChameleon, BrowserStack, SauceLabs, booting up a full VM or Docker image which possibly takes minutes. This is even more wasteful if the lifcycle is managed in a way which discards browsers after each test.

**Comment by erdi** [comment]
There are more places in `GebReportingSpec` where a new `Browser` instance will be created, [here](https://github.com/geb/geb/blob/master/module/geb-spock/src/main/groovy/geb/spock/GebReportingSpec.groovy#L36), [here](https://github.com/geb/geb/blob/master/module/geb-spock/src/main/groovy/geb/spock/GebReportingSpec.groovy#L41) and [here](https://github.com/geb/geb/blob/master/module/geb-spock/src/main/groovy/geb/spock/GebReportingSpec.groovy#L47).

Another point is that it's possible that the window for which the report will be taken even if a `Driver` instance backing the freshly created `Browser` and thus the browser driven has been been just created won't be empty if you for example [setup the initially loaded page](http://stackoverflow.com/a/34622056/1856764).

This change would be a breaking change and might sometimes be surprising - some user could be surprised that for certain tests they're not getting reports even if they asked for them.

Finally `GebReportingSpec.report(String)` and `GebSpec._browser` are public which means that you can easily override this default behaviour if you are unhappy with it.

**Comment by kriegaex** [comment]
I have already overridden the behaviour a few days ago. But I think the behaviour does not make sense. You should see my logs, they really look very strange. And on TestChameleon it takes up to five minutes to boot up a VM, it is really a pain in the *** for nothing.

**Comment by erdi** [comment]
Can I ask what is your proposed fix then? Check if `_browser` is not `null` in `GebReportingSpec.report(String)` and not generate a report at all when this is the case? Or maybe not call that method from `GebReportingSpec.cleanup()` if `_browser` is `null`? 

I struggle to see when and why `_browser` would ever be `null` if an instance is created in all the places I pointed out in my previous response. Can you please elaborate? Can you please also explain what do you exactly mean by "if `browser` is ... invalid" and how we would detect that invalidity?

**Comment by kriegaex** [comment]
Yes, of course you can ask, even though I think I already explained in my initial inquiry. I even linked to the exact place: [`GebReportingSpec.cleanup`](https://github.com/geb/geb/blob/master/module/geb-spock/src/main/groovy/geb/spock/GebReportingSpec.groovy#L44).

I thought about something like your second suggestion:

> Or maybe not call that method from `GebReportingSpec.cleanup()` if `_browser` is null?

I think it is perfectly okay and even expected to create a browser instance in `setupSpec()` or `setup()` methods because they can be expected to initialise resources (and in Geb the browser is one of the main resources). But in `cleanup()` or `cleanupSpec()` I expect resources to be cleaned up or just maybe left alone if I want to reuse them, but dfefinitely not recreated or initialised.

> I struggle to see when and why `_browser` would ever be `null` if an instance is created in all the places I pointed out in my previous response.

Well, I also mentioned that, but maybe not explained it well enough, sorry for that: I run a Maven module, the first browser test dynamically tries to create a new browser instance via a cloud test factory. There is some kind of network or service availability problem and the VM cannot be created, thus no remote web driver can be created. But the test is already running and now fails, triggering the cleanup method to be called which tries again to create a VM and corresponding browser instance. You may think that this is a rare case, but in our environment it happens many times a day. Blame it on the cloud test service we use, but it is reality and we have to deal with it. Even in a local case this can happen if for whatever reason the browser cannot be created in the first place. Why then should the cleanup method try to create it again. I think this should be left to the next test's setup or setupSpec method.

**Comment by erdi** [comment]
Yeah, now your explanation about not creating resources in `cleanup()` if they should be created beforehand but were not because of an error makes a lot of sense. Sorry for being blunt previously, not triggering a report from `cleanup()` if `_browser` is null makes a lot of sense.

**Comment by kriegaex** [comment]
Thanks, @erdi, for the quick reaction. But one question about https://github.com/geb/geb/commit/61254c6020aa3f9d3a3c39fd058e1ff9ba7cf57d#diff-ab5d5ab21b6d63d38ae1d99484778f76R47: Does the line

    } else if (!browser.config.reportOnTestFailureOnly) {

not mean that by accessing `browser` actually again `getBrowser()` is called, creating a new instance on the fly? I have not tested or carefully ready all the code, so maybe my speculation is wrong.

**Comment by erdi** [comment]
That's a good catch, thanks for reviewing. I fixed it in https://github.com/geb/geb/commit/405e20f0845b635578d4f60f62442bd5465e8466.
