### ISSUE TITLE
Strong typing for modules

### ISSUE THREAD

**Issue by topr** [geb/issues#433]
Currently for the sake of better error messages module instances are wrapped in `TemplateDerivedPageContent` class. The meaningful error message is a nice feature but loosing the module type is not really welcome.

The question is what is better - to keep the declared module type and loose better error message or the opposite?
I would be in favour of strong types, I think.

**Why not both?** That would be great but the open question then is how to implement this and is it even possible?

**Comment by topr** [comment]
@erdi

I hope I'll have time to look into this matter further as I've got impression that instead of wrapping the modules into `TemplateDerivedPageContent` for the sake of better error messages, better would be to achieve the same by injecting some 'error message assembler' into the module. What do you think?

Meanwhile i have something less game-changing. This is surely not an ultimate solution, just a slight convenience added. If user likes to keep better error messages, does nothing. If needs for any reason to unwrap then it's enough to cast it with `as` operator like.

`SomeModule module = page.theModule as SomeModule`

At least it gives the control over the type/error message decision to the user. What do you think about such addition? Shall I raise pull request? By the way, where would be a proper place to add coverage for such feature, a new Spec or any existing one?
https://github.com/geb/geb/compare/master...topr:wrapper-to-module-casting

**Comment by erdi** [comment]
There already is some [`error message assembler` injection into modules going on](https://github.com/geb/geb/blob/master/module/geb-core/src/main/groovy/geb/Module.groovy#L87). Your suggestion gave me an idea on pushing this even further [here](https://github.com/geb/geb/blob/master/module/geb-core/src/main/groovy/geb/content/PageContentTemplate.groovy#L105) and hopefully getting rid of the need for `TemplateDerivedPageContent`.

There are a couple of more methods on that class I'd need to look at before being able to get rid of it completely so I'm happy to accept a PR from you with an override for the `as` operator on `TemplateDerivedPageContent`.  With regards to a test then probably a new one called `geb.ContentUnwrappingSpec` would be the right thing to do.

**Comment by topr** [comment]
The CI failed on _internet explorerWindows8Test_. I'm not sure why though. Is it related to the introduced  change or some kind of a flickering test?

How to re-trigger build without pushing any new change?

**Comment by topr** [comment]
>Your suggestion gave me an idea on pushing this even further here and hopefully getting rid of the need for `TemplateDerivedPageContent`.

To be honest I haven't look into implementation details yet so not sure what's the effort to do that, but this was exactly the same idea I had. I need to carry on with the ongoing work now, perhaps I'll find some time to have a loon on this matter later this week though.

**Comment by erdi** [comment]
After having a look at possibly getting rid of `TemplateDerivedPageContent` it unfortunately doesn't seem to be possible. It's not only error reporting but other features like form control shortcuts on content elements and the `to` template option that depend on that class. We will therefore have to live with explicit type conversion introduced as the initial solution to this ticket.
