### ISSUE TITLE
IP whitelisting configuration

### ISSUE THREAD

**Issue by hallatech** [geb/issues#436]
Hi,

I've hit a problem where certain pages of the journey for my tests were working but have been upgraded in some environments and only accessible by IP whitelisting.
Even though I can manually access the sites and see my IP is allowed through,  when I run my tests via Gradle executing Spock tests with Geb it is getting blocked an dI can see the behaviour is the same as when my IP is not whitelisted.

How can I see what is the IP being used by Selenium/Geb/Spock/Gradle to execute the tests from and if necessary configure it to use a whitelisted IP.
I'm not sure at which part of the stack Geb/Spock/Gradle to configure.

TIA

**Comment by erdi** [comment]
This is not an issue. Please ask usage questions on the [user mailing list](https://groups.google.com/forum/#!forum/geb-user).
