### ISSUE TITLE
"unsecure connection" warning

### ISSUE THREAD

**Issue by tweinreich** [geb/issues#439]
Hi,

Can anybody tell me how to set the `ignore-certificate-errors` capability in `GebConfig.groovy` (if this is the desired way of getting rid of this error message)?
Could not find anything about that in the documentation and didn't find something useful on the web.

Thank you in advance.

**Comment by erdi** [comment]
Please ask user questions on the [user mailing list](https://groups.google.com/d/forum/geb-user).
