### ISSUE TITLE
isDisplayed from Modules always return false

### ISSUE THREAD

**Issue by m4cn** [geb/issues#441]
I have the following code : 
  
    class ApplicationPage extends Page {
     ...
    static content {
        editApp(to: EditAppPage) { appName -> $("span", text: appName).siblings("i", class: "aci-pencil") }
    }
    def editApplication(def appName) {
        editApp(appName).click()
    }
    ...
    }

> 

    class EditAppPage extends Page{
    ...
    static content {
        someModule { module SomeModule }
    }
    def openSomeModule(){
        //after click the panel will expand with form elements
        someModule.click()
        println $("switch-button", 'ng-model': contains("switchButton")).isDisplayed()    //1
        println someModule.isVisible()                                         //2 
        println someModule.isVisibleC()                                        //3
        println someModule.switchEl.isDisplayed()                              //4
        waitFor { someModule.switchEl.isDisplayed() }
    }
    ...
    }

> 

    class SomeModule extends Modules {
        static content = {
              switchEl(required: false) { $("switch-button", 'ng-model': contains("switchButton")) }
        }

    def isVisible(){
        switchEl.isDisplayed()
    }

    def isVisibleC(){
        $("switch-button", 'ng-model': contains("switchButton")).isDisplayed()
    }
    }

now in openSomeModule method I am verifying element visibility and the problem is that when I use direct selector inside this method it gives me 'true' (look 1) which is correct value but the same selector from Module gives me always 'false' which is incorrect (look 2,3,4)

The question is does Modules are initialized before and they are not reinitialized with Page ? Is it possible to have the same state of the elements as I have in Page ?   Or maybe I am doing something wrong ?

**Comment by erdi** [comment]
Closing, because this is a usage question and not an issue.

Please ask usage questions through our advertised support channel which is [the user mailing list](https://groups.google.com/d/forum/geb-user).
