### ISSUE TITLE
Geb has issues interacting with CEF

### ISSUE THREAD

**Issue by sergiofrrg** [geb/issues#442]
Hi, I use a Cucumber JVM-Geb-Selenium Framework and I decided to use it to test my CEF application. Everything works fine except when the CEF configuration includes the --off-screen-rendering-enabled parameter, which is mandatory to use in my application. In that case, a runtime error happens. 
Any idea why this is happening?

Thank you.

**Comment by erdi** [comment]
This is not an issue but a usage question. Please ask usage questions on the [user mailing list](https://groups.google.com/forum/m/#!forum/geb-user).
