### ISSUE TITLE
Not able to run in PhantomJS, where as the tests work in all other browsers. Any help will be really appreciated.

### ISSUE THREAD

**Issue by chethansjce** [geb/issues#444]
Not able to run PhantomJS, where as the code works in all other browsers.

I see this under Standard Error where I do not find an error logs:

Jul 28, 2016 11:33:46 PM org.openqa.selenium.phantomjs.PhantomJSDriverService <init>
INFO: port: 37405
Jul 28, 2016 11:33:46 PM org.openqa.selenium.phantomjs.PhantomJSDriverService <init>
INFO: arguments: [--webdriver=37405, --webdriver-logfile=/Users/Chethan/Documents/Code-base/nlcd-delivery-ui/functional-tests/phantomjsdriver.log]
Jul 28, 2016 11:33:46 PM org.openqa.selenium.phantomjs.PhantomJSDriverService <init>
INFO: environment: {}
PhantomJS is launching GhostDriver...
[INFO  - 2016-07-29T03:33:47.439Z] GhostDriver - Main - running on port 37405
[INFO  - 2016-07-29T03:33:47.839Z] Session [427eefc0-553d-11e6-9065-39881f8523e0] - page.settings - {"XSSAuditingEnabled":false,"javascriptCanCloseWindows":true,"javascriptCanOpenWindows":true,"javascriptEnabled":true,"loadImages":true,"localToRemoteUrlAccessEnabled":false,"userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X) AppleWebKit/534.34 (KHTML, like Gecko) PhantomJS/1.9.7 Safari/534.34","webSecurityEnabled":true}
[INFO  - 2016-07-29T03:33:47.839Z] Session [427eefc0-553d-11e6-9065-39881f8523e0] - page.customHeaders:  - {}
[INFO  - 2016-07-29T03:33:47.839Z] Session [427eefc0-553d-11e6-9065-39881f8523e0] - Session.negotiatedCapabilities - {"browserName":"phantomjs","version":"1.9.7","driverName":"ghostdriver","driverVersion":"1.1.0","platform":"mac-unknown-32bit","javascriptEnabled":true,"takesScreenshot":true,"handlesAlerts":false,"databaseEnabled":false,"locationContextEnabled":false,"applicationCacheEnabled":false,"browserConnectionEnabled":false,"cssSelectorsEnabled":true,"webStorageEnabled":false,"rotatable":false,"acceptSslCerts":false,"nativeEvents":true,"proxy":{"proxyType":"direct"}}
[INFO  - 2016-07-29T03:33:47.839Z] SessionManagerReqHand - _postNewSessionCommand - New Session Created: 427eefc0-553d-11e6-9065-39881f8523e0

Exception:  geb.waiting.WaitTimeoutException: condition did not pass in 60.0 seconds. Failed with exception:
Assertion failed: 

at geb.waiting.Wait.waitFor(Wait.groovy:138)
	at geb.Page.verifyThisPageAtOnly(Page.groovy:226)
	at geb.Page.verifyAt(Page.groovy:182)
	at geb.Browser.doAt(Browser.groovy:454)
	at geb.Browser.at(Browser.groovy:353)
	at geb.Browser.to(Browser.groovy:568)
	at geb.Browser.to(Browser.groovy:556)
	at geb.Browser.to(Browser.groovy:523)
	at geb.spock.GebSpec.methodMissing(GebSpec.groovy:56)

**Comment by erdi** [comment]
If it works in other browsers then I'm inclined to believe that it is a PhantomJS driver specific issue. It's hard to try to help with the amount of information provided, all I can see is that one of your conditions does not pass, but have no idea what the condition really is.

Also, [GhostDriver is currently not maintained](https://github.com/detro/ghostdriver#help-needed) and I would advise agains using it.
