### ISSUE TITLE
Geb Grails 3 Example!

### ISSUE THREAD

**Issue by aadrian** [geb/issues#452]
Please add a Grails 3 example for Geb.

This: https://github.com/geb/geb-example-gradle is based on Grails 2, and while this version it's still required (many users were not able to upgrade from Grails 2) it would help new users with new projects to have a complete working example with Grails 3 too.

Thank you.

**Comment by gijsleussink** [comment]
I think you meant to say https://github.com/geb/geb-example-grails

**Comment by erdi** [comment]
Grails 3 ships with integration for Geb and there is [an example of using Geb in Grails 3 docs](http://docs.grails.org/3.1.6/guide/testing.html#functionalTesting) which in my opinion renders a standalone example redundant.

**Comment by aadrian** [comment]
> I think you meant to say https://github.com/geb/geb-example-grails.

Yes. Thank you. I pasted the wrong URL.

> Grails 3 ships with integration for Geb and there is an example of using Geb in Grails 3 docs which in my opinion renders a standalone example redundant.

Your Grails 2 example "just works" as opposed to that help page.

That integration you mention is more for Developers and **not** for Testers. 
Selenium (and hopefully Geb) is used allot by Testers. For them a working example that can be just extended is very helpful.
