### ISSUE TITLE
Browser path in example apps!

### ISSUE THREAD

**Issue by aadrian** [geb/issues#453]
Please extend the example apps to have the browser paths configurable, so that users can override
them with their 'gradle.properties' or some other configuration options 

Thank you.

**Comment by erdi** [comment]
The point of example apps is to provide a starting point for new users and not to show every single possible use of the framework. Where would we stop with the scope of examples? Making them too complex would do more harm as it would make them harder to pick up and understand by the newcomers.

**Comment by aadrian** [comment]
> The point of example apps is to provide a starting point for new users

The point of a "starting point" is to be able to start in first place :). 
This is not the case here: these examples fail, since the browser paths are variable from machine to machine and new users will have have a very frustrating first time experience.
Some that I personally know gave up and just use Selenium directly :).

> Where would we stop with the scope of examples? 

Where they're useful for new users and not just a simple "hello world"?


> Making them too complex would do more harm ...

:).
Considering that they're only "hello world" right now, I think this "danger" is way to far :).

**Comment by erdi** [comment]
Sorry @aadrian, I misunderstood what you meant. I thought that you meant application paths but now I see that you meant browser paths.

The https://github.com/geb/geb-example-gradle project will build as long as you have chrome and firefox 46 or earlier installed anywhere on the machine. It also automatically downloads the right chromedriver and phantomjs for the OS on which it runs. There is no need to configure any paths to browsers.

**Comment by aadrian** [comment]
> The https://github.com/geb/geb-example-gradle project will build as long as you have chrome and firefox 46 or earlier installed anywhere on the machine.

It's not that simple: on many machines, the testers don't have the control over what version of the browser it's installed on the system, nor when it's updated. These browsers might be or not in the path.

The user could get a specific version of a portable version (would be nicer if Gradle would get this too), but that won't be in the path (at least not the first in the list in best case). 
So in all these cases there's a need to specify what is the correct path with the correct version of the browser in order to make the stuff work.

**Comment by erdi** [comment]
IMHO, your use case is definitely not shared with most Geb users. Most people will have their browsers installed in the default location on their machines and the example project will pick that up without any problem. Your use case is not general enough to justify making it part of this simple example project.

I also believe that providing paths to browser executables is more related to configuring the WebDriver implementation you are using than to Geb and the example project in question contains a `GebConfig.groovy` file which is a starting point to configuring them.

**Comment by aadrian** [comment]
> MHO, your use case is definitely not shared with most Geb users. 

It's not my use case but that of many testers using Selenium currently where I tried to convince them to migrate to Geb :).

> GebConfig.groovy file which is a starting point to configuring them

Than please update the default example to contain this, if it's already possible.

**Comment by erdi** [comment]
No, I will not update the default example to contain this because it's irrelevant for that project.

If you want to know how to do this then please ask a question on [the user mailing list](https://groups.google.com/d/forum/geb-user) which is the relevant place to ask for help on how to provide paths to browser executables and other similar use cases. Expecting learning how to do something like that from the example project is in my opinion unreasonable.

**Comment by aadrian** [comment]
> Expecting learning how to do something like that from the example project is in my opinion unreasonable.

And this is why people are not that eager upgrading from Selenium to Geb :).

**Comment by erdi** [comment]
And that's probably best for all of us.

**Comment by aadrian** [comment]
> And that's probably best for all of us.

Well, I don't know about that :).

I've been upgrading quite a few projects to Geb, but the feedback from the testers is in many cases not that positive as I would have expected (as a developer).

Complaints go in the direction of the not so good "first experience": examples not working for many, but I suppose many just jump to the examples without touching the very detailed documentation at all.
