### ISSUE TITLE
Discontinue Grails 2.x plugin

### ISSUE THREAD

**Issue by erdi** [geb/issues#456]
With Grails 3.0 released in March 2015 and the Grails team urging everybody to upgrade there seems to be little point in releasing new version of the Grails 2.x plugin for Geb. It will be still possible to use newer versions of Geb with Grails 2.x by it will have to by done by specifying which version of Geb is supposed to be used in `BuildConfig.groovy` file of the Grails 2.x project.

Projects using Grails 3.x can use the built-in support for Geb, see https://github.com/grails3-plugins/geb and http://docs.grails.org/3.1.6/guide/testing.html#functionalTesting.

**Comment by aadrian** [comment]
On the contrary - it's only wish thinking from the Grails Team side. Many projects won't be migrated Grails 3 since it's not backward compatible with 2 and there's also not automated migration. Not every body gets budget all the time to rewrite stuff.

**Comment by erdi** [comment]
As I said, it will still be possible to use newer Geb versions together with Grails 2.x. It's just that you won't be upgrading the version of the plugin but you will have to modify the dependencies in `BuildConfig.groovy` of your Grails application while using the 1.0 version of the plugin.

You should not expect that OSS projects will support your outdated dependencies because you "don't get the budget" to keep your whole stack up to date. If you freeze part of your stack to a certain version then be prepared that you will have to freeze other bits of it too.

**Comment by aadrian** [comment]
> because you "don't get the budget" to keep your whole stack up to date. 

It's not just me, but almost all projects I've seen are in this situation, since management usually does not accept "budget for upgrade just for the sake of it, because new versions are incompatible". 

There was zero reason for Grails 3 to be that incompatible (and require complete rewrite of apps) with 2.
This way they also made all the Grails books and courses obsolete.

**Comment by erdi** [comment]
Sorry, but this tracker is not a relevant place for your sentiments about Grails.
