### ISSUE TITLE
Unchecked checkboxes should return null and not false as their value

### ISSUE THREAD

**Issue by erdi** [geb/issues#465]
This issue is about reverting changes added to fix #156. The rationale there is that `false` can be used to uncheck a checkbox but one can also use `null` as the value when unchecking a checkbox and the manual suggests to use groovy truth when checking if a checkbox is checked.

This special case of returning false for unchecked checkboxes means that they behave inconsistently in other parts of the API, namely when obtaining value of multiple checkboxes using form control shortcuts.

Note that this is breaking change and can only be introduced in the next major version.

**Comment by Nossarian** [comment]
Documentation section 4.14.3 for the most current release still indicates that calling .value() on an unchecked checkbox will return 'false'. Please update the relevant documentation.

Thanks.

**Comment by erdi** [comment]
Thanks for reporting @Nossarian, I created a new issue for it.
