### ISSUE TITLE
geb-example-maven broken

### ISSUE THREAD

**Issue by mlem** [geb/issues#467]
Hi,

today I wanted to integrate Geb into our maven project and I was fiddeling with it for some time until I realized, that the example project is broken.

https://github.com/geb/geb-example-maven
see builds: https://app.snap-ci.com/geb/geb-example-maven/branch/master

Cheers,
Martin

**Comment by erdi** [comment]
I've just pushed a fix in geb/geb-example-maven@570a2c01a341b25d94c925a5d4acbe5c5c8a72eb.
