### ISSUE TITLE
Add local storage handling to Geb

### ISSUE THREAD

**Issue by kriegaex** [geb/issues#472]
@erdi wrote in a comment under http://stackoverflow.com/q/36527441/1082681:

> There is no code in Geb that deals with clearing local storage but apparently in latest versions in WebDriver there is a WebStorage interface which provides ability to interact with local storage. Feel free to submit issues against Geb to: expose clearing local storage functionality via a method on browser and clear local storage together with clearing cookies as part of the test lifecycle.

Because the OP did not care to create a ticket and I think it makes sense anyway, I am taking care of it so as not to let it become forgotten.

* Clearing local storage automatically or optionally before the browser/driver is closed is one thing.
* Adding a method to clear it during runtime is another.
* Even better would be other ways of iteracting with local storage, such as reading from or writing into it.

**Comment by ChrisCooney** [comment]
Just bumping this. We tend to avoid using cookies and getting easy access to local storage without running on client Javascript would be lovely! 👍
