### ISSUE TITLE
Explain resetBrowser() + clearCacheAndQuitDriver() trick in Book of Geb

### ISSUE THREAD

**Issue by kriegaex** [geb/issues#473]
After I had answered a StackOverflow question about how to restart a browser within a test [here](http://stackoverflow.com/a/42073620/1082681) in a rather complicated way and @erdi offered a much simpler solution [here](http://stackoverflow.com/a/42099443/1082681) I am creating this tracking ticket:

> OMG, this works and I had to use such a complicated workaround, searching my eyes out in the Book of Geb (BoG) and elsewhere. Would you mind adding this to [chapters 3.1 or 3.2](http://www.gebish.org/manual/current/#driver-management) where you talk about life cycle management? `resetBrowser()` is not mentioned a single time in the whole BoG, not to speak of the combination with `clearCacheAndQuitDriver()`. To document this in the BoG would be really helpful. `resetBrowser()` is also undocumented in the [JavaDoc](http://www.gebish.org/manual/current/api/geb/spock/GebSpec.html#resetBrowser()).

For reference, this is a simple use case:

```groovy
package de.scrum_master.tdd

import geb.driver.CachingDriverFactory
import geb.spock.GebReportingSpec

class RestartBrowserIT extends GebReportingSpec {
  def "Search web site Scrum-Master.de"() {
    when:
    go "https://scrum-master.de"
    report "welcome page"

    then:
    $("h2").text().startsWith("Herzlich Willkommen bei Scrum-Master.de")

    when: "browser is reset"
    resetBrowser()
    CachingDriverFactory.clearCacheAndQuitDriver()

    and: "download page is opened in new browser"
    go "https://scrum-master.de/Downloads"
    report "download page"

    then: "expected text if found on page"
    $("h2").text().startsWith("Scrum on a Page")
  }
}
```

**Comment by kriegaex** [comment]
I took a quick look over your commit. The test case looks more condensed and elegant than mine, the text is also comprehensive. Thanks!

**Comment by erdi** [comment]
Thanks for your feedback, Alexander!
