### ISSUE TITLE
Migrate CI from away Snap CI

### ISSUE THREAD

**Issue by erdi** [geb/issues#474]
Because it is shutting down.

**Comment by antony** [comment]
Happy to migrate this to CircleCI for you - or did you have another CI in mind?

**Comment by erdi** [comment]
I was thinking about using GitLab CI.

**Comment by antony** [comment]
Any specific reasons other than familiarity? After some significant
analysis I've found circle to be the fastest, easiest and most reliable.
It's also free.

I'll look at gitlab for comparison.

**Comment by erdi** [comment]
And I will have a look at Circle CI...

**Comment by erdi** [comment]
Migrated to [Gitlab CI](https://gitlab.com/gebish/geb/pipelines).
