### ISSUE TITLE
FireFox 52.0.2 on MAC OSX (10.12.4) does not connect

### ISSUE THREAD

**Issue by kaceyarnold** [geb/issues#479]
[FF-debug-output.txt](https://github.com/geb/issues/files/917966/FF-debug-output.txt)

PhantomJS works
Chrome 57 works
I can open the browser and go to www.gebish.org with FF
I just started playing with the example today(04/12/17). No changes have been made to anything.
groovy -version
Groovy Version: 2.4.8 JVM: 1.8.0_121 Vendor: Oracle Corporation OS: Mac OS X

**Comment by erdi** [comment]
This is most probably a configuration issue and not a problem with the library. Please follow up on the mailing list if the suggestion I just posted in a response to your message does not work.
