### ISSUE TITLE
Navigator.filter is case sensitive

### ISSUE THREAD

**Issue by rickirunge** [geb/issues#482]
Just found that Navigator.filter(selector) is case sensitive for tag names.

**Example:**
Let's say I have a button on the page, like this
```
<button>hello</button>
```

It seems the find method is not case sensitive, as both of these finds the button
```
navigator.find("BUTTON")

navigator.find("button")
```

If i use then add the filter method something stange happens:
```
def buttons = navigator.find("BUTTON")

buttons.filter("BUTTON") // This will filter away the button, even though it was just found using the exact same selector

buttons.filter("button") // But if I use a lowercase selector the button is not filtered away
```

I would expect that if I use the exact same selector in filter as used in find, then I wouldn't have any effect on the result.
But I seems the case matters for filter and doesn't matter for find.

**Comment by erdi** [comment]
Fixed in https://github.com/geb/geb/commit/54a7a43da637253282c1db749e1f3f8acff8db56
