### ISSUE TITLE
www.gebish.org is offline

### ISSUE THREAD

**Issue by tveronezi** [geb/issues#487]
I'm sorry if this is the wrong place to create this kind of issue. I don't know where to do it as I have no access to the geb site. 

Your website seems to be offline for at least one full day. 

<img width="931" alt="screen shot 2017-06-01 at 9 59 55 am" src="https://cloud.githubusercontent.com/assets/1918442/26683221/18e9ee88-46b1-11e7-9c97-6c6e8d4442d1.png">

**Comment by erdi** [comment]
See https://github.com/geb/issues/issues/486
