### ISSUE TITLE
GebReportingTest (Junit) does not report failures

### ISSUE THREAD

**Issue by darionct** [geb/issues#491]
Due to the order of JUnit execution of rules and life-cycle methods (`@After`), Geb does not report failures because `failureTracker` flag is set AFTER `writeGebReport()` is called so it will never be true.

This issue is similar to the #445. Possible solution is explained in https://github.com/junit-team/junit4/issues/906 , but it is not simple since the `browser` instance is null when the TestWatcher is called.

**Comment by erdi** [comment]
Thanks for reporting, I will look into it, sounds like a possible issue. Testing code that is participating in test framework's lifecycle is sometimes hard to get right.
