### ISSUE TITLE
Failure when trying to change the page and currentURL cannot be converted to URI 

### ISSUE THREAD

**Issue by savagekrosa** [geb/issues#492]
I happened to encounter this issue when I tried to turn my tests from using separate Browser instance for each test to single browser instance for each suite. After one of the tests ends, several other tests fail with java.net.URISyntaxException. After investigating, it seems that URL in the browser generated by angular is not a valid url to convert to URI, so when calling:

`browser.to MyPage`

I receive the exception once it gets to the "Browser.go" method and it tries to convert currentUrl to URI:

`currentUri = currentUrl ? new URI(currentUrl) : null` -> this will throw java.net.URISyntaxException

I report this as an issue, because I believe the fact that currentURL cannot be converted to URI should not end in complete failure and instead "Browser.go" method should continue (as it does for NullPointerException)

**Comment by erdi** [comment]
Thanks for reporting.

 Would you mind sharing what was the url that caused the issue? It will help me to understand it and hopefully come up with a better solution.

**Comment by savagekrosa** [comment]
Hi

I didn't share url cause it is not a public url, however here is the format of url (replaced words with letters "abcd" and numbers with "1234", otherwise it is the same url):

`http://abcd1234.abcd.abcd.com:1234/ab-cd/index.html#!/abcd#abcd-abcd-abcd-abcd`

**Comment by erdi** [comment]
Thx @savagekrosa, I see what the problem is with the URL - using unescaped `#` inside of the fragment part is not allowed. Anyway, I will need to figure out a way to gracefully handle invalid urls in that particular part of the codebase.
