### ISSUE TITLE
Add support for using methods defined on TouchActions inside of interact {} blocks

### ISSUE THREAD

**Issue by erdi** [geb/issues#497]

**Comment by dpost** [comment]
@erdi have you given any thought to implementing this? I am currently looking at overriding the default Geb behavior to do this on an Appium project, but I'd love to work out a real solution

**Comment by erdi** [comment]
Yes, I looked into it cause you asked. ;)

The idea is to add a `touchInteract {}` method which will be using a delegate which extends from the current `geb.interaction.InteractDelegate` and is backed by `org.openqa.selenium.interactions.touch.TouchActions`. 

The above has to be done because `TouchActions` are only supported on `WebDriver` instances that also implement `org.openqa.selenium.interactions.HasTouchScreen`. As far as I can see, at the moment this is the case only for `ChromeDriver` so we cannot modify `interact {}` to support touch actions.

I had a look at Appium and I'm afraid that adding support for `org.openqa.selenium.interactions.touch.TouchActions` to Geb will be of little use to you because Appium is using it's own mechanism for supporting touch actions (see `io.appium.java_client.TouchAction`) and not the built-in one from WebDriver API (`org.openqa.selenium.interactions.touch.TouchActions`). You could **probably** get it to work if you used the technique described at http://www.softpost.org/en_US/android-automation-with-appium/performing-touch-actions-in-android-web-app/.

**Comment by erdi** [comment]
After having a closer look at this it seems that the only driver implementing `org.openqa.selenium.interactions.HasTouchScreen` and therefore supporting `org.openqa.selenium.interactions.touch.TouchActions` is `ChromeDriver`. 

Given how tricky it is to even test it let alone use it (instances of chrome provided from both SauceLabs and BrowserStack over `RemoteWebDriver` don't seem to support it and both providers use appium for providing real mobile devices which has it's own touch actions support in the form of `io.appium.java_client.TouchAction`) I believe there is little value in adding support for `TouchActions` in `interact {}`-like blocks into Geb. The fact that [appium considers `org.openqa.selenium.interactions.touch.TouchActions` api to be very constrained and hence coming up with their own api](http://appium.io/docs/en/writing-running-appium/touch-actions/) seems to confirm my view on this.
