### ISSUE TITLE
Enable logger for geb

### ISSUE THREAD

**Issue by kavmaria** [geb/issues#500]
While doing each action need to update logger like as 

27-9-2017 00:00:12 click //button[@name='name' ]
27-9-2017 00:00:12 enter //input[@name='name' ] values 'testing' 

I should be able to enable logger for each action

**Comment by erdi** [comment]
Can you please elaborate? Is this a usage question or a feature request?

**Comment by kavmaria** [comment]
Thanks for quick response .

Suppose I need to automate login test case  into a application .

Step 1 : open URL  : https :// report.com 
Step 2 : Enter username  : Kaveri
Step 3 : Password : kaveri
Step 4 : Submit form 
Here  
 While doing each action into need capture in audit log  so that while debug the failure analyses , I look logger file  to confirm input & corresponding OBJECT Repository (xpath or css ) correct or not  .  No need to write logger in specification class for each action instead of  is there any way enable all action need to capture my logger file for debug the action and input values in geb class itself

**Comment by erdi** [comment]
Sorry, but you still did not provide an answer to my previous comment. Is this a usage question or feature request?

**Comment by kavmaria** [comment]
This a usage question only

**Comment by erdi** [comment]
Please ask usage questions on the [user mailing list](https://groups.google.com/d/forum/geb-user)
