### ISSUE TITLE
clicking on non existent element does not throw error

### ISSUE THREAD

**Issue by stuplum** [geb/issues#501]
Given this page:

```groovy
class SomePage {
    ...
    static content = {
        button(required: false) { $('.some-incorrect-selector').module(SomeButtonModule) }
        ...
    }
}
```

and given this Spec:

```groovy
class SomeSpec {

    def 'Clicking on the button should take user to AnotherPage' () {

        given:
            def page = to SomePage

        when:
            page.button.click()

        then:
            at AnotherPage
    }
}
```

**Expected behaviour:**
An exception should be thrown when the button element is missing and can't be clicked.

**Actual behaviour:**
When the button doesn't exist on `SomePage` the test is still reaching the `at` check for `AnotherPage`

**Comment by erdi** [comment]
Created from the following mailing list thread: https://groups.google.com/forum/#!topic/geb-user/pYqGUq9oHq4.
