### ISSUE TITLE
withFrame(frame, Closure) always returns null

### ISSUE THREAD

**Issue by Foxcon84** [geb/issues#508]
Similar to withWindow always returning null, withFrame experiences the same behaviour. One workaround for it right now is to add || true after the withFrame block.

**Comment by erdi** [comment]
I could not reproduce and also [added an explicit test for checking values returned from `withClosure()`](https://github.com/geb/geb/blob/467851ccc7b3fdd41ff7563fd17d487925c2ff3c/module/geb-core/src/test/groovy/geb/frame/FrameSupportSpec.groovy#L212).

Feel free to reopen if you indeed observe this issue and can provide more detail on how to reproduce, preferably even a unit test that would expose it.
