### ISSUE TITLE
Element In IE requires a 2nd click to click element

### ISSUE THREAD

**Issue by sean-oneill-rockalltech** [geb/issues#511]
Please avoid submitting usage questions as issues and use the user mailing list at https://groups.google.com/forum/#!forum/geb-user instead.

Hi Just a quick question with a problem I am having with Geb at present.

I am trying to select an element id on the IE page but for some reason, in order for the element to be selected it needs to be clicked twice as the first .click() does not find the element. I have added in waits to see if this would be a timing issue but it still doesn't solve the problem at the moment.  Any help would be great.

**Comment by erdi** [comment]
Given the information you provided it looks to me like this is more of a usage question than an issue with Geb. Please ask your question on [the user mailing list](https://groups.google.com/forum/#!forum/geb-user).
