### ISSUE TITLE
Test on Safari/Mac do not work using BrowserStack

### ISSUE THREAD

**Issue by rnemeth1980** [geb/issues#513]
Using
        **groovyVersion = '2.4.7'
        gebVersion = '2.0'
        seleniumVersion = '3.6.0'**
on Win8.1 with
```
        safari {
            capabilities os: "OS X", os_version: "Sierra"
        }
```
The screenshot taken is showing
**Safari Can't Open the Page**
**Safari can't open the page "https://www.123.com/". The error is: "WebKit encountered an internal error" (WebKitErrorDomain:300)**
Tests with Firefox on Mac are working.

**Comment by erdi** [comment]
This is not a Geb issue but a BrowserStack issue. I would suggest contacting BrowserStack support, they are very responsive. It will speed things up if you provide the id of the session in which the error occurred.
