### ISSUE TITLE
Geb with Testng. Running in Parallel not invoking multiple browsers

### ISSUE THREAD

**Issue by mmanikandan88** [geb/issues#514]
My Tests are extending GebReportingTest(TestNg). When I run the testng file with classes as parallel , I can see the classes getting executed in parallel but only one browser has been opened.
It looks like the browser is shared between the tests. Could you please advise how to launch multiple browsers.

**Comment by erdi** [comment]
Please do not post usage questions as issues and use [user mailing list](https://groups.google.com/forum/#!forum/geb-user) instead.
