### ISSUE TITLE
Generate a new minor release to include latest changes

### ISSUE THREAD

**Issue by thewarpaint** [geb/issues#515]
Would it be possible to generate a minor release to include the latest changes, specially https://github.com/geb/geb/commit/7d26fe555fa7e04b417a99102ee22042b08ee495 (Added a form control module for date input)? I think a lot of users would benefit from it.

Thanks a lot!

**Comment by erdi** [comment]
You'll be pleased to know that [2.1 has just been released](https://groups.google.com/forum/#!topic/geb-user/iZmVTk2I4to).

**Comment by thewarpaint** [comment]
Perfect, thanks!
