### ISSUE TITLE
Feature request: Add an option to work with # in URL as not a fragment.

### ISSUE THREAD

**Issue by otsvetkov** [geb/issues#516]
Add an option to work with # in URL as not a fragment.

Our application using urls like `http://<site.com>/#/<internalApplication>?<queryString>`
geb 1.0 works fine, but for geb >1.0

1. When I'm using `queryString` 
and open `to MyInternalApplication, queryString`  (static url = 'http://<site.com>/#/<internalApplication>')
Then final URL looks like
`http://<site.com>/?<queryString>#/<internalApplication>`

2. If I'm using direct URL (`queryString` already inside URLs) 
When I open `http://<site.com>/#/<internalApplication2>?<queryString>` from `http://<site.com>/#/<internalApplication1>?<queryString>`
Then there is unnecessary reload after `sameUrlWithDifferentFragment(currentUri, newUri)` in `go` method of `Browser.groovy`

**Comment by erdi** [comment]
I’m on holidays atm, I will have a look when I’m back.

**Comment by erdi** [comment]
Sorry for the massive delay in responding.

I understand that it is a breaking change but according to URI specification, everything after the first `#` is a fragment and even if part of the fragment is what looks like a query string it will not be treated as such but just as a part of the fragment. I consider the fact that query string is appended before the fragment in Geb > 1.0 to be the correct behaviour.

My suggestion would be to switch to using dynamic fragment computation with parameterised pages as shown in [Pages > Advanced page navigation > URL fragments](http://gebish.org/manual/current/#advanced-page-navigation-url-fragments) section of the manual. That would allow you dynamically build the fragment as required including its "query string"-like part yet still keep your `to()` calls clean and simple.

With regards to your second point - the contract of `go()` and `to()` is that calling them will always cause a page load so the behaviour you're describing is as expected.

**Comment by otsvetkov** [comment]
Thank you for the response! I will try dynamic fragment computation.

The second point means that all of my pages (to <Page>) will be loaded twice in place: 
```
driver.get(newUri.toString())
if (sameUrlWithDifferentFragment(currentUri, newUri)) {
    driver.navigate().refresh()
}
```
Once on `driver.get(newUri.toString())`
The second on the next line.
But I don't need reloading the page, it is already loaded. :)

**Comment by erdi** [comment]
We could add a config property not to refresh the page if navigating to the same url with different fragment. If that would be sufficient for you then please create a new issue for adding the config property and close this one.
