### ISSUE TITLE
setting disabled checkbox not throwing UnableToSetElementException

### ISSUE THREAD

**Issue by rosemead** [geb/issues#517]
Hi.
Attached is a couple of tests added-on geb.NavigableSpec to demonstrate the issue: Attempting to write onto a disabled input throws a/m exception, whereas attempting to untick a disabled-and-ticked checkbox does not.
Thanks!

[Attempting_to_set_disabled_text,checkbox_should_yield_an_exception.zip](https://github.com/geb/issues/files/1769926/Attempting_to_set_disabled_text.checkbox_should_yield_an_exception.zip)

**Comment by erdi** [comment]
I applied your patch but it does not match your description. According to your passing test, attempting to modify a disabled text input throws an `InvalidElementStateException` and not `UnableToSetElementException` as you imply. `UnableToSetElementException` is only thrown if you are trying to set value of an element that is not an input, a select or a textarea so I would not expect it to be thrown in any of the scenarios you mention.

**Comment by erdi** [comment]
Closing due to no reply from the OP.

Please feel free to reopen if you would like to discuss this further, @rosemead.
