### ISSUE TITLE
Matrix URL notation is not supported

### ISSUE THREAD

**Issue by Uniqen** [geb/issues#519]
Matrix URL notation is used extensively in Angular applications. This is not supported in Geb. 

As a workaround one can use driver.get(..) instead of go(url) and driver.get(..) + at(Page) instead of to(Page) but it would be nice with official support.

**Comment by erdi** [comment]
Can you please be more specific about what exactly is not supported with
regards to matrix URLs in Geb and what support for it you would like to
see? It is unfortunately unclear to me from your original report.

**Comment by erdi** [comment]
Closing due to no reply from the OP.

If you are willing to provide more information regarding your request please feel free to reopen it, @Uniqen.
