### ISSUE TITLE
innerNavigatorFactory not working for Page content

### ISSUE THREAD

**Issue by DuskoV** [geb/issues#521]
if I have custom innerNavigatorFactory in config, it's not used in Page.content definitions.

**Sample GebConfig entry:**

```
innerNavigatorFactory = { Browser browser, List<WebElement> elements ->
    elements ? new CustomNonEmptyNavigator(browser, elements) : new EmptyNavigator(browser)
}
```

**Page example:**

```
class PgStates extends Page {
    static at = { true }

    static content = {
        pageNavigation { $('#navigation') }
    }
}

```
When I use later, pageNavigation will be of type NonEmptyNavigator instead of CustomNonEmptyNavigator , as defined 

```
at(PgStates) {
pageNavigation.hello()
}
```

This will fail if hello() is declared in CustomNonEmptyNavigator , because objects in "content" of page are created as NonEmptyNavigator

**Comment by erdi** [comment]
I do not think there is an issue here. 

You are right that content elements will not be of `CustomNonEmptyNavigator` type but neither they will be of `NonEmptyNavigator` type. They are actually instances of `TemplateDerivedPageContent` which implements `Navigator` and [delegates all missing method calls to it's internal `_navigator` field](https://github.com/geb/geb/blob/ae6f6b896c2215d983f0b4ad70b45d6d137906cb/module/geb-core/src/main/groovy/geb/content/TemplateDerivedPageContent.groovy#L94) which in your example will actually be an instance of `CustomNonEmptyNavigator`.

As shown in the test I added in https://github.com/geb/geb/commit/ae6f6b896c2215d983f0b4ad70b45d6d137906cb methods defined in custom `Navigator` implementations can be called on content elements without problems.
