### ISSUE TITLE
The path to the driver executable must be set by the webdriver.gecko.driver system property

### ISSUE THREAD

**Issue by yuexia-wuyimin** [geb/issues#522]
Please avoid submitting usage questions as issues and use the user mailing list at https://groups.google.com/forum/#!forum/geb-user instead.

I configured the system according to the api document and run the demo
but it went run
![image](https://user-images.githubusercontent.com/6943339/39301101-969e3b68-4980-11e8-8cb7-c2b45392f9f9.png)

I want to know if I need to configure gecko's path to make it right

**Comment by erdi** [comment]
This is not an issue but a usage question.

Please conform to the kind request not to post usage questions as issues and ask it instead on the mailing list at https://groups.google.com/forum/#!forum/geb-user.
