### ISSUE TITLE
geb/geb-example-gradle - Unable to load class 'org.gradle.api.provider.Provider' in intelliJ - upgrade com.energizedwork.*

### ISSUE THREAD

**Issue by dave00galloway** [geb/issues#523]
The geb-example-gradle project will not load in IntelliJ IDEA as-is. The build.gradle file contains outdated dependencies that are no longer available:-

`    id "com.energizedwork.webdriver-binaries" version "1.0" `

`     id "com.energizedwork.idea-base" version "1.2"`

this results in the following error when trying to import the gradel project into intelliJ -

```
FAILURE: Build failed with an exception.

* Where:
Build file '/Users/dave/git/geb_example_gradle/geb-example-gradle/build.gradle' line: 4

* What went wrong:
An exception occurred applying plugin request [id: 'com.energizedwork.webdriver-binaries', version: '1.0']
> Failed to apply plugin [id 'com.energizedwork.webdriver-binaries']
   > Could not generate a proxy class for class com.energizedwork.gradle.webdriver.WebDriverBinariesPluginExtension.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 0.223 secs

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/dave/git/geb_example_gradle/geb-example-gradle/build.gradle' line: 4

* What went wrong:
An exception occurred applying plugin request [id: 'com.energizedwork.webdriver-binaries', version: '1.0']
> Failed to apply plugin [id 'com.energizedwork.webdriver-binaries']
   > Could not generate a proxy class for class com.energizedwork.gradle.webdriver.WebDriverBinariesPluginExtension.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 0.369 secs
Cause: org.gradle.api.provider.Provider

```

this is fixable by changing the versions:-

```
    id "com.energizedwork.webdriver-binaries" version "1.4"
    id "com.energizedwork.idea-base" version "1.4"
```

resulting in a successful import and build in intelliJ-

```
:wrapper UP-TO-DATE

BUILD SUCCESSFUL

Total time: 0.419 secs

BUILD SUCCESSFUL

Total time: 0.332 secs
```

**Comment by erdi** [comment]
Thanks for the report. You were most probably getting that error because a version of Gradle newer than 4.2 (which is the one for which Gradle Wrapper was installed in that project) has been used when importing the project into IntelliJ. It would work fine if only you used the wrapper to generate IntelliJ project setup...

    ./gradlew idea

and then imported the project into IntelliJ via the generated `geb-example-gradle.ipr`.

I have nevertheless merged your pull request and also updated the wrapper to 4.7 in that project while at it.
