### ISSUE TITLE
Drag and drop issue in Geb

### ISSUE THREAD

**Issue by nareshkaruru** [geb/issues#529]
I am trying to drag and drop an element from one location to another, But its not working. I have tried using the below interact module. 
interact {
    clickAndHold($('#element to be dragged'))
    moveByOffset(165, 0)
    release()
}
I would really appreciate if someone can help me with this issue!

**Comment by erdi** [comment]
@nareshkaruru, please do not ask usage questions by creating issues. Please ask your question on the Geb user mailing list at: https://groups.google.com/forum/#!forum/geb-user instead.
