### ISSUE TITLE
Update to Groovy 2.5

### ISSUE THREAD

**Issue by erdi** [geb/issues#534]

**Comment by sporkisfaster** [comment]
Is there any update on this, is it just a matter of a pom update or would 2.5 have breaking changes on Geb?

**Comment by erdi** [comment]
There are no breaking changes of Groovy 2.5 that would affect Geb that I’m
aware of. It is likely that the latest version will work if you run it with
Groovy 2.5 on the classpath. Bear in mind though that current version is
built and tested with Groovy 2.4 so there are no guarantees it will work
with 2.5.

Note that work has already started on benefiting from changes in Groovy 2.5
in Geb’s internals and it lcan be seen in groovy-2.5 branch of the repo.
The plan is to incorporate it in the upcoming 3.0 release of Geb which I’d
like to get out of the door by mid May.
