### ISSUE TITLE
Book of Geb: anker link for chapter 7.2.4 leads to 2.2.1

### ISSUE THREAD

**Issue by kriegaex** [geb/issues#535]
When clicking on the headline of chapter "7.2.4. Base URL", you are taken to chapter [2.2.1. The base URL](http://www.gebish.org/manual/current/#base-url) instead, obviously because they both have the same anker "#base-url". I noticed when trying to send someone on StackOverflow a link to 7.2.4 and it did not work. So I sent him a link to [7.2.3](http://www.gebish.org/manual/current/#driver-caching-configuration) instead and told him to scroll down, which is a bit awkward.

I suggest to fix this little glitch by assigning two different anker IDs.

**Comment by erdi** [comment]
Thanks for reporting. I'll add a check which will fail the build if there are anchors with the same ids in the manual so this does not happen again and then I'll fix it.

**Comment by kriegaex** [comment]
I took a quick look over your commit. Looks good to me. I like the fact that you have an automated test in order to detect future regressions. This is in the spirit of Spock and Geb. ;-) Thank you.

**Comment by erdi** [comment]
And the added benefit of having the automated test is that I found one more
instance where the ids were not unique apart from the one that you reported.
