### ISSUE TITLE
Add support for JUnit 5

### ISSUE THREAD

**Issue by erdi** [geb/issues#539]

**Comment by moghaddam** [comment]
Any update on this one?

**Comment by erdi** [comment]
No, not at the moment but thanks for showing interest, it will help to prioritise.

**Comment by sporkisfaster** [comment]
I think with the advent of Spock moving to JUnit 5 this is now a bit critical.

**Comment by erdi** [comment]
Spock being built on top of JUnit 4 or 5 has not impact here. This ticket is about adding support for writing tests directly in Jupiter. But I agree, this is long overdue.

**Comment by tilmanginzel** [comment]
Hi @erdi :), 

> Spock being built on top of JUnit 4 or 5 has not impact here.

It seems like it has at least a small impact on test reporting. I am maintaining [geb-spock-reports](https://github.com/AOEpeople/geb-spock-reports) (which is built on-top of [spock-reports](https://github.com/renatoathaydes/spock-reports)). While adding support for Spock 2 and JUnit 5, an issue in the reports arised (see: https://github.com/AOEpeople/geb-spock-reports/issues/28#issuecomment-634837940).

It boils down to `gebReportingSpecTestName` being always `null`, as the `@Rule TestName` is not supported in JUnit 5: https://github.com/geb/geb/blob/master/module/geb-spock/src/main/groovy/geb/spock/GebReportingSpec.groovy#L26

Am I missing something obvious, or is a new version of the geb-spock module required to fix this? Thanks in advance. :)

**Comment by erdi** [comment]
Hi @tilmanginzel,

Thanks for reporting. Yes, this is indeed a JUnit 5 incompatibility, and one that I would have not considered before. Looks like I will have a bit of a challenge to make `geb-spock` both JUnit 4 and JUnit 5 compatible. Maybe `geb-spock-2.0` will be needed if all else fails, we'll have to see. 

I think that this issue is now really ripe enough and I might as well get to it sooner rather than later. In my defence, adding JUnit 5 compatibility will require some breaking changes, a major release and a bit of thinking around how to keep the great Geb support working in IntelliJ. So it's not as trivial as it might seem from the outside.

**Comment by tilmanginzel** [comment]
> adding JUnit 5 compatibility will require some breaking changes, a major release and a bit of thinking around how to keep the great Geb support working in IntelliJ. So it's not as trivial as it might seem from the outside.

No worries, take the time you need! :) A new major version seems to be reasonable if cross-support for both JUnit 4 and 5 is not so easy.

I just found a great workaround for the issue I have mentioned above. Spock provides a [`spock-junit4`](https://github.com/spockframework/spock/tree/master/spock-junit4/src/test/groovy/org/spockframework/junit4/junit) compatibility module, which was mentioned in their [release notes](http://spockframework.org/spock/docs/2.0-M2/release_notes.html#_new_junit_platform). Just adding the dependency provides `@Rule TestName` annotation support! This seems to fix my issue for now. :)

**Comment by mkutz** [comment]
Just ran into the same issue. It could be fixed by removing the `@Rule` and replacing `gebReportingSpecTestName?.methodName` with `specificationContext.currentIteration.name`. The latter works for both: Spock 1.3 and 2.0-M1.

**Comment by kriegaex** [comment]
May I ask @erdi as well as everyone else here if this means that 4.0.-rc-1 can be used with Spock 2.x (2.0-M4 as of today)? Normally I would just try, but I am a bit busy and would only begin to change my playground project with many Spock and Geb sample tests, different web drivers etc. if it is worth the effort. I would rather not play around for 3 hours, only to find out that it is still too early to try. Spock 2.0-M4 is very stable, there are no major issues and IMO it has many bugfixes and improvements which will never be ported back to 1.3.

**Comment by tilmanginzel** [comment]
Hi @kriegaex, so far I have only tested Spock 2.0-M2 with Geb 3.4, which worked very well (adding `org.spockframework:spock-junit4:2.0-M2-groovy-3.0` did the trick). I haven't tested newer versions so far.

**Comment by erdi** [comment]
Unfortunately @kriegaex, Geb 4.0 will still be Spock 1.x compatible. It might or might not work with Spock 2.x but it has not been tested thus it is not officially supported. You will most likely have to use the compatibility artifact as suggested by @tilmanginzel for a start.

Two things to note:
- support for JUnit5 and Spock 2.x are somewhat orthogonal even if Spock 2.x is built on JUnit5 - that's because support for each framework (and each major version of the framework, if there is more than one version supported) comes in a separate module and they are all independent
- I only plan to add support for Spock 2.x after a final version is released, see #619
