### ISSUE TITLE
File upload causes duplicates to be uploaded

### ISSUE THREAD

**Issue by amitaashok** [geb/issues#544]
When uploading multiple files using the documentation as the reference ( $("form").csvFile = uploadedFile.absolutePath), I face an issue of duplicates when I call this multiple times.
I upload 3 files (file1, file2, file3), however there are 6 files uploaded (file1, file1, file2, file1, file2, file3).
Each time, the previous file is uploaded again.

This only happens on Firefox and here are my versions: Geb version: '2.2',
Selenium version: '3.14.0', Gecko driver: '0.23.0', Firefox: 63.0.1

Currently as a workaround, I clear the element after each file upload (i.e. csvFile.firstElement().clear() )

**Comment by erdi** [comment]
Can you please provide more context? What do you mean by duplicate uploads? It is not clear what exactly it is that you are doing, what you are expecting to happen and what is happening.

**Comment by amitaashok** [comment]
Hi, I'm trying to automate the upload of 3 files in our application. We have a single area to upload file attachments. Hence, I upload by assigning the absolutePath to the input element (upload control). 
(As per the below reference:  http://www.gebish.org/manual/1.0/#file-upload)

Expected result: I expect the 3 files to be uploaded.
file 1 
file 2
file 3
Actual result: There are 6 files uploaded (duplicates of the same files are uploaded).
file 1, 
file 1, file 2
file 1, file 2, file 3
The element retains the previously uploaded file and uploads it again, which is incorrect. So, file 1 is uploaded thrice and file 2 twice.

Hope it's more clear now.

**Comment by erdi** [comment]
Sorry, but that doesn’t make it clearer to me. I would appreciate some
code. My biggest question is do you assign three files to the input in one
go and then send them or do you assign, send, assign, send, assign, send
and if there is a page reload after sending? Is it just a regular form that
you’re posting or are you using some js library and the post is done using
ajax?

Also, can you confirm that it works in an unexpected way only in Firefox
and works as expected in other (which?) browsers?

**Comment by amitaashok** [comment]
It's a multiple file dropzone. So, I assign each file separately. There is no page reload after sending. This is the library we are using - https://react-dropzone.js.org/

The automation selector is -
 fileUpload(required: false, wait: true) { fileUploadZone.find('input', type: 'file') }
       
The below Geb method is called 3 times in a loop, once for each file.
 def uploadFileForOrder(folder, fileName) {
        waitFor { attachFileButton.displayed }
        Path fileToPrintPath = Paths.get(folder + fileName)
        String filePath = fileToPrintPath.toAbsolutePath().toString()
        fileUpload = filePath
        waitFor { uploadedFile(fileName).displayed }
    }

It works on Chrome and IE 11. Used to work on Firefox before I upgraded Geb.

**Comment by erdi** [comment]
Thank you, this is useful and now I have some information to go on. One
last question - do you by any chance remember what is the version of Geb
you upgraded from and can you please confirm what version you upgraded to?

**Comment by amitaashok** [comment]
Hi, no worries :) I upgraded Geb version 0.13.1 to version 2.2

**Comment by amitaashok** [comment]
I have the below workaround for Firefox in the method now, which ideally shouldn't be required. Hence, I raised the issue.

  if (browserName == 'firefox') {
       try {
              fileUpload.firstElement().clear()
        }
        catch(InvalidElementStateException e) {
         }
}

**Comment by erdi** [comment]
Thanks for confirming the versions!

**Comment by erdi** [comment]
Is this still an issue, @amitaashok?

**Comment by erdi** [comment]
Closing due to no response from the OP.
