### ISSUE TITLE
Add missing text-like input types

### ISSUE THREAD

**Issue by mkutz** [geb/issues#548]
Since there are already several implementations (e.g. [SearchInput](https://github.com/geb/geb/blob/master/module/geb-core/src/main/groovy/geb/module/SearchInput.groovy), [TelInput](https://github.com/geb/geb/blob/master/module/geb-core/src/main/groovy/geb/module/TelInput.groovy) or [EmailInput](https://github.com/geb/geb/blob/master/module/geb-core/src/main/groovy/geb/module/EmailInput.groovy), there should be a corresponding implementation for all types listed [here](https://www.w3schools.com/tags/att_input_type.asp).

Missing are
- ~[color](https://www.w3schools.com/tags/att_input_type_color.asp)~ not text-like, will be put in separate issue
- ~[datetime-local](https://www.w3schools.com/tags/att_input_type_datetime-local.asp)~ not text-like, will be put in separate issue
- ~[image](https://www.w3schools.com/tags/att_input_type_image.asp)~ not text-like, will be put in separate issue
- ~[month](https://www.w3schools.com/tags/att_input_type_month.asp)~ not text-like, will be put in separate issue
- [number](https://www.w3schools.com/tags/att_input_type_number.asp)
- [password](https://www.w3schools.com/tags/att_input_type_password.asp)
- ~[range](https://www.w3schools.com/tags/att_input_type_range.asp)~ not text-like, will be put in separate issue
- ~[time](https://www.w3schools.com/tags/att_input_type_time.asp)~ not text-like, will be put in separate issue
- [url](https://www.w3schools.com/tags/att_input_type_url.asp)
- ~[week](https://www.w3schools.com/tags/att_input_type_week.asp)~ not text-like, will be put in separate issue

**Comment by mkutz** [comment]
I'd provide a PR in the next days if nobody has any objections against this issue.

**Comment by erdi** [comment]
I have no objections and I’m looking forward to the PR.

**Comment by mkutz** [comment]
I'm trying to write the needed tests and found the [DateInputSpec](https://github.com/geb/geb/blob/master/module/geb-core/src/test/groovy/geb/module/DateInputSpec.groovy) as a template for the `DateTimeLocalInputSpec`. How can I execute that test? Is there a way to do it without Sauce Labs?

See [311dbfc](https://github.com/mkutz/geb/commit/311dbfc1c1fcf6d640651fbe56e64605e62dc36c)

**Comment by erdi** [comment]
There probably is but not a straightforward, out of the box one. SauceLabs
offers free accounts with a limit of automation time, I’d just try using
that if I were in your position.

Also, note that DateInputSpec is somewhat special - it caters for the fact
that the module it tests only works in a subset of browsers. For modules
handling controls that are supported in all browsers including HtmlUnit I’d
model the tests after specs like TextInputSpec.

**Comment by mkutz** [comment]
> Also, note that DateInputSpec is somewhat special - it caters for the fact
that the module it tests only works in a subset of browsers. For modules
handling controls that are supported in all browsers including HtmlUnit I’d
model the tests after specs like TextInputSpec.

I picked `DateInputSpec` for exactly that reason. The `datetime-local` input is not even supported by Firefox.

**Comment by mkutz** [comment]
I get the following error for the more "fancy" input types of `ColorInput`, `DateTimeLocalInput`, `MonthInput`, `RangeInput` and `TimeInput`:

```
org.openqa.selenium.InvalidElementStateException: invalid element state: Element must be user-editable in order to clear it.
```

I guess there is something missing in Selenium or in the browsers' web driver, rather then in Geb. What do you think @erdi?

I'd like to reduce the scope of this issue to the missing text-like input types (`NumberInput`, `PasswordInput` and `UrlInput`

**Comment by erdi** [comment]
It will be most likely due to this line: https://github.com/geb/geb/blob/3e0ada5065856a7ef1576eae5f25fdcf0e41bb7e/module/geb-core/src/main/groovy/geb/navigator/NonEmptyNavigator.groovy#L713. Note how I had to put in [a special case for `date` inputs](https://github.com/geb/geb/blob/3e0ada5065856a7ef1576eae5f25fdcf0e41bb7e/module/geb-core/src/main/groovy/geb/navigator/NonEmptyNavigator.groovy#L709).

I'm more than happy for you to reduce the scope to `NumberInput`, `PasswordInput` and `UrlInput` because I know that the more fancy controls are not so straightforward to support - I experienced it when adding a module for `date` inputs. I wanted to suggest working on it one by one initially but didn't want to curb your enthusiasm...

**Comment by mkutz** [comment]
Just found the line. I'll check if that works.

I'll reduce the scope anyway and open one new issue per fancy input.

The commits I did I'll cherry-pick for other PR's.

**Comment by mkutz** [comment]
I had some trouble running the snippets on my machine:

```
org.openqa.selenium.WebDriverException: newSession
Build info: version: '3.12.0', revision: '7c6e0b3', time: '2018-05-08T14:04:26.12Z'
System info: host: 'digital0507', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '4.18.0-12-generic', java.version: '1.8.0_191'
Driver info: driver.version: FirefoxDriver
remote stacktrace: stack backtrace:
   0:           0x4f388c - backtrace::backtrace::trace::h736111741fa0878e
   1:           0x4f38c2 - backtrace::capture::Backtrace::new::h63b8a5c0787510c9
   2:           0x442d88 - webdriver::error::WebDriverError::new::hea6d4dbf778b2b24
   3:           0x44cecc - geckodriver::marionette::MarionetteSession::response::h98d048d51a7ee2ba
   4:           0x42c729 - <webdriver::server::Dispatcher<T, U>>::run::hba9181b5aacf8f04
   5:           0x402c59 - std::sys_common::backtrace::__rust_begin_short_backtrace::h19de262639927233
   6:           0x40c065 - std::panicking::try::do_call::h6c1659fc4d01af51
   7:           0x5e38ec - panic_unwind::__rust_maybe_catch_panic
                        at /checkout/src/libpanic_unwind/lib.rs:98
   8:           0x420d32 - <F as alloc::boxed::FnBox<A>>::call_box::h953e5f59694972c5
   9:           0x5dc00b - alloc::boxed::{{impl}}::call_once<(),()>
                        at /checkout/src/liballoc/boxed.rs:661
                         - std::sys_common::thread::start_thread
                        at /checkout/src/libstd/sys_common/thread.rs:21
                         - std::sys::imp::thread::{{impl}}::new::thread_start
                        at /checkout/src/libstd/sys/unix/thread.rs:84
```

Probably nothing related to my changed, so I created the PR anyway.
