### ISSUE TITLE
Improve execution for real browser tests

### ISSUE THREAD

**Issue by mkutz** [geb/issues#555]
Currently several tests cannot be executed in HTML Unit. 

For contributors the easiest way to execute these tests is to create an account at Sauce Labs and use the limited free testing minutes.

A way to improve this could be a profile relying on Docker based Selenium containers or on locally installed browsers. An example can be found in my [geb-testing-workshop](https://github.com/mkutz/geb-testing-workshop/).

**Comment by erdi** [comment]
This has been superseded by https://github.com/geb/issues/issues/575
