### ISSUE TITLE
Improve OnFailureReporter

### ISSUE THREAD

**Issue by thokari** [geb/issues#565]
Hello, 

I have the problem that my Specs don't produce screenshots when they fail.

I tracked the problem down to this method in `geb.spock.OnFailureReporter`:

```
    void error(ErrorInfo error) {
        if (error.method.kind == FEATURE) {
            try {
                spec.reportFailure()
            } catch (Exception e) {
                //ignore
            }
        }
    }
```

In my case the value is `ITERATION_EXECUTION`, so this doesn't write a screenshot.
The `@Retry` annotation is responsible for this, but I would argue that using this annotation should not break this basic behaviour.
It would also be generally nice, if the information about the type of method would go into the name of the screenshot, rather than not taking it.

Would you consider a Pull-Request, that improves this method to better handle setup/cleanup/iteration/other failures?

**Comment by erdi** [comment]
I'll gladly accept a PR fixing it for your particular use case as long as you provide a [test using EmbeddedSpecRunner](https://github.com/geb/geb/blob/master/module/geb-spock/src/test/groovy/geb/spock/GebReportingSpecSpec.groovy#L210) with your PR which fails unless the fix is applied. 

On the other hand I'd argue that failures in setup/cleanup should not be reported on as they are usually unrecoverable problems and not test failures. If you disagree then please open a separate issue to discuss further and let's focus on fixing your particular issue as part of this ticket.

**Comment by thokari** [comment]
I submitted a PR containing a test that shows the problem.
As you can see, the behaviour actually depends on the `Mode` in which the `@Retry` is used.
This might throw people off, specifically as automatically retrying UI tests for whatever reason is a common thing to do.
Flaky tests, although undesirable, should not be denied.

For this reason I think that there should exist a straightforward way to automatically report on failing setup / cleanup methods as well.
I will eventually open a new issue, but I wanted to solve this first, as you suggested.

I am suggesting that the the `OnFailureReporter`, together with the Spock Extension of similar name might be a bit overly specific.
In my own code I solved the problem, by creating another global Spock Extension and another Reporter, that would report on `MethodKind.ITERATION_EXECUTION`, as well as setups and cleanups.
I called them `OtherThanFeatureOnFailureReporter` and `OtherThanFeatureReportingOnFailureExtension`.
That solved the issue for me, but it felt a bit like shooting birds with cannons.

**Comment by thokari** [comment]
Not to forget mentioning that I bumped Spock to 1.2 to make `Retry` available in the first place.

**Comment by thokari** [comment]
I noticed a general problem here, which comes from the fact that the `GebSpec` resets the `_browser`  in its`cleanup` method' , making it `null` before the reporter can access it.

However, this is also partly controlled by `@Stepwise`, which in my own code I am using in every spec, but it is not used in the tests that I provided for this issue.

**Comment by thokari** [comment]
I pushed another commit, to include combinations of `@Retry` and `@Stepwise` with data driven tests.

I realised that in some cases, we would need to change things in Spock, but this is probably out-of-scope for this ticket.
The point is that we probably cannot let the browser stay open, while retrying a test, because it is such an expensive resource.
So I specified some of the cases, where no report is produced as "expected".
I do think, however, that it would be good practice to emit some kind of message if that happens, I did to `stderr` in this case.

Other than that, I only removed the `MethodKind.FEATURE` restriction on the reporter, to make the rest of the tests pass.

In this current form, the PR *would* fix my problem, but I am curious about your opinion.

**Comment by thokari** [comment]
Could you possibly elaborate on the decision to forward the call to `OnFailureReporter#error` back to the `GebReportingSpec`. Is there another reason besides implementing the test counter logic?

Would you possibly consider to let the reporter itself take care of that, and calculate the screenshot names from the `ErrorInfo` instead of keeping track of the numbers separately?

This could potentially fix the bug in the numbering scheme, in the `@Stepwise` + `@Retry` + data driven combination.

It also would fix the problem, that codenarc complains about to me right, which is not making use of `ErrorInfo`.

**Comment by erdi** [comment]
First of all thank you for spending the time to investigate this and submitting a quality PR. Sorry for taking so long to reply properly but this is complicated and I needed some time to dive into this to fully understand what is happening when `@Retry` is being used.

There is a number of things I'm uneasy about in all this. 

Firstly, I'd rather not bump the version of Spock used to compile against as it is potentially a breaking change. I can work around it by adding a compatibility module for Spock 1.2 the same way we currently have for Spock 1.0 (`:compatibility:spock-1.0`). I would then myself move the tests that you've added to that new module after accepting your PR. I'm happy to do that. Also note that Geb 3.0 is on the horizon so we will be moving toward using Spock-1.2 relatively soon but not just yet.

Secondly, and that's a bigger issue in my mind, I don't think that you are aware of how and when `IRunListener.error(ErrorInfo)` is being called if you use `@Retry`:
1. If you use `@Retry` with `ITERATION` or `FEATURE` on a non-parameterised feature method then `error()` is called once as soon as a failure within the feature method occurs -> with current implementation you will get a report generated for every failed retry as expected at the time of the failure
2. If you use `@Retry` with `ITERATION` on a parameterised feature then `error()` is called once after every failed iteration within the feature method -> with current implementation you will get a report generated for every failed retry of every iteration as expected at the time of the failure
3. If you use use `@Retry` with `FEATURE` on a parameterised feature method then `error()` is called as many times as there were failed iteration attempts but **after the execution of the all, possibly retired iterations** -> currently you will not get a report when using `OnFailureReporter` and with your suggested changes you will get as many reports as there were failed iteration attempts if there was at least one iteration failed in the last retry but they will all be the same and **might even not contain a state after a failure if the last executed iteration was successful**; you will also get no reports at all if in the last retry all iterations were successful
4.  If you use use `@Retry` with `SETUP_FEATURE_CLEANUP` for a non-parameterised feature then `error()` method is called after cleanup occurs -> currently no report is generated for this and with the changes you're suggesting get as many reports as there are retries but they will be all the same, will be generated after the last retry and **might even not contain a state after the failure if part of the cleanup changed the state of the browser**; you will also get no reports if at least one retry is successful
5. If you use use `@Retry` with `SETUP_FEATURE_CLEANUP` for a parameterised feature then `error()` method is called as many times as there are retries after the cleanup of the last retry of an iteration for each iteration that has failed all of the retries and zero times for any iteration for which at least one retry has succeeded -> currently no report is generated for any failed iteration attempts and with the changes you're suggesting you will get as many reports as there are retries for all iterations for which all retries failed but they will all be the same for an iteration and **might even not contain a state after the failure if part of the cleanup changed the state of the browser**; you will also get no reports for each iteration for which at least one retry has succeeded

I know that what I wrote is quite a lot to digest and it's also hard to explain so I'm expecting things to be unclear and you possibly having to ask questions to be able to understand. If you disagree with any of the points above I'm happy to prove my points with some tests.

I would argue that the current situation is correct in that it does not generate error reports when it's not able to do so at the time of the failure in the feature before any cleanup occurs or any iterations or retries happen. Could it be improved? Maybe, but it would probably need to be made aware of `@Retry` and even then, the current implementation of it seems to be lacking the necessary extension points to be able to be notified at the point at which a failure that will then be retried occurs.

Please let me know what you think of all that.

**Comment by thokari** [comment]
I understand and mostly agree. I was also checking the calls to `error(ErrorInfo)`, when I noticed that it gets called "irregularly", to put it that way, but I failed to realise exactly the parts you put in bold writing. I also do get the feeling that this is even more of a Spock issue than I thought originally.

I think it is very worth it to specify this with tests, I think the tests that are in my PR could be extended to show what you wrote.

As a next step, I am considering to extend the tests with actual page stubs, and verify the content of the reports, as to not make the mistake of accepting wrong screenshots or html dumps.

Feel free to give further suggestions.

**Comment by erdi** [comment]
One suggestion I have for now is to please hold off with putting any more work into this. I will reply to your latest message later tonight.

**Comment by erdi** [comment]
I appreciate your willingness to add tests confirming or debunking what I wrote. My worry is that it's going to be a significant amount of work, especially if you go to the length of verifying report contents as you suggest and I'd like us to come up with some kind of a plan before you put in the effort. I personally don't see how we can take meaningful failure reports when `@Retry` with `FEATURE` mode on a parameterised feature or with `SETUP_FEATURE_CLEANUP` mode is used. I think your current approach of just removing the condition on method kind in `OnFailureReporter.error()` will not cut it. So, to save you the wasted effort of writing these tests I'd like to see if you have any ideas on how we could actually make Geb's failure reporting work in these cases.

**Comment by thokari** [comment]
I concur that my approach of removing that condition is not the solution.

Instead of returning with `proceed`ing with the invocation of the intercepted method, could it be an option to make the `IMethodInterceptor` that is the `OnFailureReporter` inspect the result, and "prematurely" call `report` on the spec in the relevant cases?
Also, please clarify on what you mean by "necessary extension points".

**Comment by erdi** [comment]
By "necessary extension points" I mean any mechanism in `RetryExtension` and the listeners it introduces which would allow us to plug in code which would be notified at the exact point when a failure happens instead of being informed only when all of the retries have failed like in some scenarios now.

I think your idea about not using `AbstractRunListener.error()` and using `IMethodInterceptor.intercept()` is highly likely to work and actually a better solution in the first place. What I'd do first is to change `geb.spock.ReportingOnFailureExtension.visitSpec()` to install `OnFailureReporter` as an interceptor to into all feature methods of all specs, that is `spec.allFeatures*.featureMethod*.addInterceptor(reporter)` and change `OnFailureReporter` to take the report in `intercept()`. If after that change on master all test still pass then I would revert, beef up test coverage to verify that reports are taken at the right time when using `@Retry` and then reapply the change with the expectation that the newly added tests go from red to green.

What do you think?

**Comment by thokari** [comment]
Allright, when I get back to this toward the end of the week, I will investigate more the behaviour of intercept, and have a go at a solution.

I will also change the tests again so that they expect reports for every test (iteration) failure.

**Comment by thokari** [comment]
I think I am hitting a bit of a wall here.
The problem, as I see it, is that the global extensions, like the reporting, in Spock get to add their interceptors before the annotation-driven ones, as is `@Retry`.
Basically as you said earlier, the way this is implemented with `@Retry`, no interceptor or listener can apparently get called between any two retried runs.

I think the problem is that the interceptors get called in the order they are added, so basically one could say that the reporter wraps the retry.

I am going to do more experiments, for example I am considering to add my own `@RetryReporting` and see if that can do the trick.

**Comment by erdi** [comment]
Do I understand correctly that this is only a problem for `@Retry` in `ITERATION` mode? Did you think about using `AbstractRunListener.error()` for `ITERATION` mode (as that seemed to work for the original implementation) and `IMethodInterceptor.intercept()` for all other modes? Did you register the interceptor onto `featureMethod`s like I suggested?

**Comment by thokari** [comment]
I am trying out all the listeners.
I am registering them like this:
```
spec.allFeatures*.featureMethod*.addInterceptor(new ReportOnFailureInterceptor())
spec.allFeatures*.addIterationInterceptor(new ReportOnFailureIterationInterceptor())
spec.addListener(new ReportOnFailureListener())
spec.addCleanupInterceptor(new ReportOnFailureCleanupInterceptor())
```
For the interceptors, I wrapped the `proceed` call in a `try`-`catch`-block, printing a debug statement before, after, and inside the `catch`.
Inside the actual test, I print `current try: <number>`

This is what the output looks like for the three cases:
`Retry.Mode.ITERATION`
```
before feature listener called
iteration interceptor called
interceptor called
current try: 1
current try: 2
failure caught by interceptor: There were 2 errors:
  org.spockframework.runtime.ConditionNotSatisfiedError(Condition not satisfied:

false
)
  org.spockframework.runtime.ConditionNotSatisfiedError(Condition not satisfied:

false
)
testCounter: 1, reportCounter: 1
error called
error called
cleanup interceptor called
cleanup interceptor over
iteration interceptor over
after feature listener called
```

`Retry.Mode.FEATURE`
```
before feature listener called
iteration interceptor called
interceptor called
current try: 1
current try: 2
failure caught by interceptor: There were 2 errors:
  org.spockframework.runtime.ConditionNotSatisfiedError(Condition not satisfied:

false
)
  org.spockframework.runtime.ConditionNotSatisfiedError(Condition not satisfied:

false
)
testCounter: 1, reportCounter: 1
error called
error called
cleanup interceptor called
cleanup interceptor over
iteration interceptor over
after feature listener called
```

`Retry.Mode.SETUP_FEATURE_CLEANUP`
```
before feature listener called
iteration interceptor called
interceptor called
current try: 1
interceptor over
cleanup interceptor called
cleanup interceptor over
interceptor called
current try: 2
interceptor over
cleanup interceptor called
cleanup interceptor over
failure caught by iteration interceptor
testCounter: 3, reportCounter: 1
error called
error called
after feature listener called
```

**Comment by erdi** [comment]
Interesting, so basically it looks like we could only make it work for `Retry.Mode.SETUP_FEATURE_CLEANUP`. 

To make it work for everything, we would need to ensure that we are the last registered interceptor even though that feels hacky and a slippery slope... But still, that's the only way that comes to my mind. So, given what you have, instead of registering `ReportOnFailureInterceptor` in the extension, let's try to install it from `ReportOnFailureListener.beforeFeature()` and see what is printed then. 🤞

**Comment by erdi** [comment]
What about this issue and the accompanying PR, thokari? Do you still intend to work on this? Just wondering if it's still worth keeping them open...

**Comment by thokari** [comment]
I was not allowed to comment here on this issue so I couldn't write anything.
You can close this PR, I cannot really justify the effort to fix this the way `@Retry` works in Spock.
The way easier solution is to just *not use* `setup` and `cleanup` methods when using `@Retry`...

**Comment by erdi** [comment]
Thanks for doing your best, I think we both learned a lot about Spock thanks to you working on this PR so it’s not all wasted effort.
