### ISSUE TITLE
Wait uses Double instead of Number

### ISSUE THREAD

**Issue by mkutz** [geb/issues#570]
I stumbled upon this while playing around with `@CompileStatic`. I noticed that every call like this `browser.waitFor(3) { myPage.button }` failed while `browser.waitFor(3d) { myPage.button }` works since the interface of `waitFor` actually requires a Double parameter.

Even without `@CompileStatic` Idea cannot determine the return type of `waitFor` and assumes `Object`, which prevents a lot of auto-completion and causes several warning in the IDE.

I don't see any reason why `Wait` cannot use `Number` instead of `Double` to fix this. If there are no objections, I'd file a PR for this.

**Comment by erdi** [comment]
No objections from me. This part of the api is very old (it was probably
written in 2009 or 2010) and the choice of the type probably wasn’t the
wisest.

This will be a backwards incompatible change but given that the next
release will be 3.0 that’s completely fine, we just need to mark it as a
breaking change in the changelog in the manual.

**Comment by mkutz** [comment]
Why do you think it won't be backwards compatible? Number is a super-type of Double, so calling `waitFor` with Doubles will still work.

**Comment by erdi** [comment]
Sorry for a late response, I've been on holiday.

You are probably right, changing from `double` to a wider type of `Number` is not a breaking change.

**Comment by mkutz** [comment]
I'm just back from Greach as well.
