### ISSUE TITLE
future-feature: modify DOM through Geb

### ISSUE THREAD

**Issue by rdmueller** [geb/issues#571]
It would be great if one could highlight elements which are clicked, before a screenshot is taken.

I could imagine that this could be done by applying a style to the element in the current DOM.

**Comment by erdi** [comment]
DOM modifications are not possible directly via WebDriver APIs. DOM can be modified by executing some javascript in the browser though and Geb has [support for running javascript](http://gebish.org/manual/current/#executing-arbitrary-code) and even [provides some sugar if the driven page contains jQuery](http://gebish.org/manual/current/#jquery-integration).

Given how easy it is to modify DOM using the above means and how generic your feature request is I'm reluctant to add anything specific for it into Geb. I appreciate the use case you provided in the issue but can you please provide rationale why it would be a good idea to add it to core, what the API could look like and why what's already there in this regard does not meet your needs?

**Comment by rdmueller** [comment]
Hi Marcin,

thanx, I wasn't aware of this feature. I guess it is enough to implement my use case!
