### ISSUE TITLE
How to wait for element until disappear/timer loaded completely 

### ISSUE THREAD

**Issue by pallavkrishna** [geb/issues#574]
Please avoid submitting usage questions as issues and use the user mailing list at https://groups.google.com/forum/#!forum/geb-user instead.
how to wait until  " **body div[class='loading-panel row']**"(available in timer)  disappear

![Screenshot (309) - Copy](https://user-images.githubusercontent.com/49298720/56353086-3d4bcf80-61ee-11e9-8aa7-e211c676a47e.png)

**Comment by erdi** [comment]
Please avoid submitting usage questions as issues and use the user mailing list at https://groups.google.com/forum/#!forum/geb-user instead.
