### ISSUE TITLE
Page should use its simple name for contentPath

### ISSUE THREAD

**Issue by leonard84** [geb/issues#583]
`geb.Page#getContentPath` should return `[getClass().simpleName]` instead of empty.

**Comment by erdi** [comment]
The `getContentPath()` method comes from `geb.content.PageContentContainer` which also contains `getRootContainer()`. That method will return the page object for content which is anchored on pages and a module instance for content not anchored on pages and should be used to build the name for the root content node representing the root container. Not including the name of the root container in `getContentPath()` and instead providing access to the root element via `getRootContainer()` provides much greater flexibility - it's up to the user to decide how they want to represent the root container, for example they can choose to use fully qualified class name or the simple class name.
