### ISSUE TITLE
Add a way to listen for navigator events

### ISSUE THREAD

**Issue by leonard84** [geb/issues#585]
We currently use Groovy MOP interceptor magic to intercept calls to `click`, `sendKeys`, `at` and `value`, in order to record a screenshot before and after a click, as well as which element was acted upon.

While it certainly works, it would be better to have an officially supported way of hooking into these events.

**Comment by erdi** [comment]
Hey @leonard84, I'm currently working on this feature request. Would you please clarify why you are intercepting calls to `at`? Is it to act on page changes (as in ["Page change listening"](https://gebish.org/manual/current/#page-change-listening)) or do you actually need a callback before and after at checking for a page occurs? If it's the latter we could introduce a `onAtCheckFailure` which would allow users to implement whatever additional reporting they'd like to have on at check failures rendering #584 redundant.

**Comment by erdi** [comment]
@leonard84, FYI, I've extracted the bit about `at` into #590 as it doesn't have much to do with `Navigator`, really.

**Comment by aptester** [comment]
@erdi I would like to use the hooking mechanism requested by @leonard84 as well. Unlike @leonard84, I haven't figured out how to get Interceptor magic working to intercept those methods but as an intermediate step have defined a custom navigator which overrides those methods in the Navigator class. But with my approach, TemplateDerivedPageContent events can't be intercepted.
