### ISSUE TITLE
Maven build breaking with 3.0 + Groovy 2.5.x

### ISSUE THREAD

**Issue by mkutz** [geb/issues#586]
My Maven is no longer working since updating to 3.0 with the following error:
```plain
[ERROR] Failed to execute goal on project geb-testing-workshop: Could not resolve dependencies for project de.assertagile.workshop:geb-testing-workshop:jar:1.0-SNAPSHOT: Failure to find org.codehaus.groovy:groovy-all:jar:2.5.6 in http://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]
```

Apparently Maven tries to pull Groovy 2.5.6 as JAR.

Project code at https://github.com/mkutz/geb-testing-workshop, full build log at https://travis-ci.org/mkutz/geb-testing-workshop/builds/540774328.

I can of course add an exclusion for `org.codehaus.groovy:*`, but I think the behavior is generally unwanted.

**Comment by Ch0j1n** [comment]
There is an Error in ```geb-*.pom.xml```

```
 <dependency>
      <groupId>org.codehaus.groovy</groupId>
      <artifactId>groovy-all</artifactId>
      <version>2.5.6</version>
      <scope>compile</scope>
</dependency>
```
is missing ```<type>pom</type>```
