### ISSUE TITLE
Browser events tracking 

### ISSUE THREAD

**Issue by darionct** [geb/issues#589]
For better understanding of what happens during lengthy tests, I wanted to capture screenshot for every page change, button click or field value change. That is particularly useful for single-page web apps. 

I would like to propose a feature which would enable test developers to listen to such events and react as they whish (write some value to the log or take a screenshot). Idea is to add a listener to the ```browser``` object and implement logic to handle the event:

```
browser.addNavigationListener([onNavigation: { source ->
  //source is the Page object
  log.debug("we are going to " + source.getClass().getSimpleName().toString())
}] as geb.navigator.NavigationListener)

```

Implementation is available in my own fork: [event casting and listeners ](https://github.com/darionct/geb/commit/4212fe7c7f99cb18bc987bd7bab8464d5c49bc66).

If you find ti acceptable, I can submit a pull request. Please, comment.

**Comment by LeoNerdoG** [comment]
I looked at this and i think that this is an interesting feature. 
Definitely very useful if you have a long-running test. 
I vote for merging this! 😄

**Comment by erdi** [comment]
Hi @darionct,

Thanks for offering to open a PR with the changes from your fork. It's a good start but it will need some work before we could merge it in, namely:
- documenting it in the manual for discoverability
- tests
- ability to set it up via the configuration mechanism (`GebConfig.groovy`/`geb.Configuration`)
- tightening up the types around callbacks

I'd be more than happy to guide you through what's needed as you don't seem to be the only person who would benefit from such feature (see #585). We could start by you opening a PR with the changes that you have in your fork and me leaving comments.

**Comment by darionct** [comment]
Thanks, I've subimtted PR 153 and will be happy to follow your guidelines.

**Comment by erdi** [comment]
Duplicates #585.
