### ISSUE TITLE
Default value for boolean isCacheDriverPerThread() is incorrect in API Docs

### ISSUE THREAD

**Issue by namuller30** [geb/issues#592]
The API docs (https://gebish.org/manual/current/api/) stated default value for isCacheDriverPerThread() is true.  If you look at the code you can see that the actual default value is false.
```
    boolean isCacheDriverPerThread() {
        readValue('cacheDriverPerThread', false)
    }
```
The docs should be updated to say that the default value is false.

**Comment by namuller30** [comment]
Also looks like the documentation in the code is wrong in Configuration.groovy.

This got me thinking though wouldn't it make more sense for the default value of this property actually be false?

**Comment by erdi** [comment]
Thanks for reporting, @namuller30. I've fixed the mistake in the javadoc for that method which incorrectly stated that this configuration option is set to `true` by default.
