### ISSUE TITLE
Switch cloud driver factories to use https urls 

### ISSUE THREAD

**Issue by erdi** [geb/issues#599]

**Comment by pail-Rider** [comment]
Hi @erdi This is a very timely improvement as my security team have just picked up that my browserstack creds are being sent via http rather than https. Is there a timescale for when this will go into a release?

**Comment by erdi** [comment]
I currently do not have a timescale for the next release. Thankfully you don't need it, simply add a class in your project which extends `BrowserStackDriverFactory`, override the `assembleProviderUrl()` method to return the same thing as in geb/geb@de97e5a and then use that new class instead of using `BrowserStackDriverFactory`.

**Comment by pail-Rider** [comment]
aha yes of course. That worked a treat. Thanks @erdi for the quick response and all the work you do on this project. It's much appreciated.
