### ISSUE TITLE
Latest version of Browserstack Tunnel has different 'success' message

### ISSUE THREAD

**Issue by mgalos999** [geb/issues#607]
The Browserstack Tunnel is downloaded, launched and killed by the gradle-browserstack plugin.
When the tunnel is launched, the output text is checked for a specific success message.
Currently this text is `You can now access your local server(s) in our remote browser.`.
However Browserstack have released a new version of the tunnel where the period is missing at the end of the message. `You can now access your local server(s) in our remote browser`
This makes the plugin timeout as it doesn't find the exact text.

https://github.com/geb/geb/blob/master/integration/geb-gradle/src/main/groovy/geb/gradle/browserstack/BrowserStackTunnel.groovy

Looks like just the period needs to be removed and it will fix this problem while maintaining backward compatibility.
`final String tunnelReadyMessage = 'You can now access your local server(s) in our remote browser.'`
to
`final String tunnelReadyMessage = 'You can now access your local server(s) in our remote browser'`

**Comment by erdi** [comment]
Thanks for reporting and the detailed analysis, @mgalos999.

**Comment by garkinv** [comment]
@erdi Sorry for rushing, do you have any ETA for 3.4 release?

**Comment by erdi** [comment]
I think that with this and #608 a release will be in order sometime this week.

**Comment by garkinv** [comment]
@erdi stuck with gradle dependencies update after 3.4 release
`> Could not resolve all artifacts for configuration ':classpath'.
   > Could not find org.gebish:geb-gradle:3.4.
     Searched in the following locations:
         https://repo.maven.apache.org/maven2/org/gebish/geb-gradle/3.4/geb-gradle-3.4.pom
         https://repo.maven.apache.org/maven2/org/gebish/geb-gradle/3.4/geb-gradle-3.4.jar
         https://plugins.gradle.org/m2/org/gebish/geb-gradle/3.4/geb-gradle-3.4.pom
         https://plugins.gradle.org/m2/org/gebish/geb-gradle/3.4/geb-gradle-3.4.jar`

And needed files aren't present here: https://repo.jfrog.org/artifactory/libs-release-bintray/org/gebish/geb-gradle/3.4/

**Comment by erdi** [comment]
Apologies for that, @garkinv, it should now be resolvable: https://search.maven.org/artifact/org.gebish/geb-gradle/3.4/jar.

Publishing to Maven Central was flaky on Saturday morning when I was trying to release the first time and I obviously got it wrong on the second attempt.

**Comment by garkinv** [comment]
Yep, it works now, thank you!
