### ISSUE TITLE
Documentation for ranges is displayed wrongly

### ISSUE THREAD

**Issue by Vampire** [geb/issues#623]
An image says more than a thousand words, so here you are:
![grafik](https://user-images.githubusercontent.com/325196/101496580-38f79b80-396a-11eb-9a88-dfa610ee258d.png)
![grafik](https://user-images.githubusercontent.com/325196/101496646-4c0a6b80-396a-11eb-96a0-d57a5744aa76.png)
So the dots are  there, but the first is attributed to the number and is not shown as there are no digits after the dot or something like that. If I add a number after the `lit` dot it becomes displayed, if I move the dot where it belongs into the `pun` block it is also displayed.

**Comment by erdi** [comment]
Thanks for reporting but this is how this renders for me on Chrome on MacOS:

<img width="459" alt="Screenshot 2020-12-09 at 20 37 59" src="https://user-images.githubusercontent.com/205451/101684600-953be780-3a5e-11eb-9da6-e41a9900573c.png">

So it looks like this might be specific to your environment. Any chance you can try and check in a different browser to see if it's any different? Note that this site is generated using a stock standard asciidoctor template (even if the version of asciidoctor has not been updated for a while) and prettify as the source highlighter - I would expect this to affect many documents if there was a problem with this basic setup.

**Comment by Vampire** [comment]
Well, it looks better in Chrome, also here, but still wrong actually.
Also in Chrome there is `lit` `0.` and `pun` `.` instead of `lit` `0` and `pun` `..`.
That makes the colors wrong, both dots should be yellowish, not the first blueish:
![grafik](https://user-images.githubusercontent.com/325196/101756502-5fd2e080-3ad6-11eb-9010-364cde89766a.png)

That the dot disappears seems to be a combination of the dot being in the wrong span and me having FiraCode as monospaced font in Firefox. `..` is a ligature in FiraCode where the two dots are drawn together to better show them as operator. But that does not harmonize too well with those wrong spans. If you look very close at my first screenshot, there is still the left-most pixel of the blue dot visible.

So the actual problem is the same, the first dot is in the wrong span which makes it appear in the wrong color and if Firacode is used as font also makes it almost disappear.

**Comment by Vampire** [comment]
It seems prettify is no longer maintained and it does not actually support Groovy but works relatively fine by using some other grammer. It is not listed as supported language nor by language supported with extension and the request to add Groovy in https://github.com/googlearchive/code-prettify/issues/1 was closed as wont-fix and the same in https://github.com/googlearchive/code-prettify/issues/586 was just ignored.

**Comment by Vampire** [comment]
It seems both builtin alternatives CodeRay and highlight.js have support for Groovy, though in CodeRay it is in beta state.

**Comment by Vampire** [comment]
In the Spock docs we actually use coderay

**Comment by erdi** [comment]
Thanks for looking into this, Björn, I will take a stab at some point at switching it over to coderay if that's what Spock's docs are using and they do not suffer from the issue.

**Comment by erdi** [comment]
Does [this](https://gebish.org/manual/snapshot/#indexes-and-ranges) look any better for you now, @Vampire? I switched to coderay. The only downside I've noticed is that the name of `$()` method is highlighted using a different colour (I think it has something to do with coderay thinking it's not a method but part of interpolated string) but I think can live with it if it makes ranges display for you better. ;)

**Comment by Vampire** [comment]
Yes, looks fine now:
![grafik](https://user-images.githubusercontent.com/325196/104111641-9c1b7b80-52e4-11eb-938b-925b5a44ca6b.png)
Thanks.

Given the class of the `$` I think it is a CodeRay bug that should be reported:
![grafik](https://user-images.githubusercontent.com/325196/104111693-7642a680-52e5-11eb-81f1-63637af68c62.png)

**Comment by Vampire** [comment]
https://github.com/rubychan/coderay/issues/253

**Comment by erdi** [comment]
Thanks for reporting it to coderay!
