### ISSUE TITLE
Support other annotations like Stepwise

### ISSUE THREAD

**Issue by masooh** [geb/issues#624]
`geb.spock.GebSpec#isSpecStepwise` is used to prevent the reset of the browser in cleanup.

I've created another Spock extension which behaves like the Stepwise extension (all feature methods are executed sequentially): https://github.com/1and1/spock-order-extension. For this annotation `#isSpecStepwise` must also return true.

Therefore the marker annotations should be configurable.

**Comment by erdi** [comment]
Hi @masooh,

[Geb 4.0 has been released today](https://groups.google.com/g/geb-user/c/QTSnbXPEiX4) and it comes with [GebTestManager](https://github.com/geb/geb/blob/master/module/geb-core/src/main/groovy/geb/test/GebTestManager.groovy) which contains test management code for all of the test frameworks Geb integrates with. The constructor of that class takes a predicate which should return `false` for classes for which `browser` should not be reset between test methods. [In Spock integration there is a builder for instances of `GebTestManager` which configures it to not reset `browser` for `@Stepwise` specs](https://github.com/geb/geb/blob/master/module/geb-spock/src/main/groovy/geb/spock/SpockGebTestManagerBuilder.groovy). If you wish to change this behaviour then you will simply need a base class similar to:
```
class OrderedGebSpec extends GebSpec {

    private final static GebTestManager TEST_MANAGER = new GebTestManagerBuilder()
            .withResetBrowserAfterEachTestPredicate { 
                !it.isAnnotationPresent(Stepwise) && !it.isAnnotationPresent(Order)
            }

    GebTestManager getTestManager() {
        TEST_MANAGER
    }

}
```

I believe that this fulfils your requirements, doesn't it?

**Comment by erdi** [comment]
Closing due to no reply from the issue author.
