### ISSUE TITLE
Parallel execution is not working properly while using Spock framework & GEB

### ISSUE THREAD

**Issue by DaniP13** [geb/issues#645]
**Preconditions**
Use default setup of GEB along with Spock framework 
SpockConfig file contains: runner { parallel { enabled true } }
GebConfig file contains:
cacheDriverPerThread = true 
System.setProperty("webdriver.chrome.driver", "path to chromedriver.exe")
driver = {new ChromeDriver()}

Test class is a child of a custom test manager class that extends GebReportingSpec
_Note:_ go baseUrl is used in the test manager class to open a specific page.
CustomPage (e.g LoginPage) class is a child of a class manager that extends Page from Geb 

**Steps to reproduce:** 
Having the setup from above try to execute multiple tests in parallel using the new feature of Spock https://spockframework.org/spock/docs/2.0-M4/parallel_execution.html **NOT** executing them via Gradle 

**Expected results** 
Based on the config, tests must be executed in multiple threads. The new browser instances opened must be instantiated with proper tests. Please keep in mind that the new feature allow the features(tests methods) to be executed CONCURRENT that means you can have test class running in parallel but in the same time features(tests methods) from each test class running in parallel. 

**Actual results**
Multiple browser instances are opened but only one is instantiated with all the tests, and the tests are executed in the same time in the same browser instance. The remaining browser instances are stuck having in the URL only the base url defined in the GebConfig file or the word: _data;_ 

Side notes: A new discussion was also opened here: https://groups.google.com/g/geb-user/c/xhqqhzDDfwM

**Comment by erdi** [comment]
As described in https://groups.google.com/g/geb-user/c/xhqqhzDDfwM/m/kjLeZRzrAwAJ this is a known limitation and there are currently no plans to change that.

**Comment by erdi** [comment]
Reopening, see https://groups.google.com/g/geb-user/c/xhqqhzDDfwM/m/L5wN1lNaBgAJ.

**Comment by DaniP13** [comment]
Thanks @erdi for the fix provided in v5.1, but unfortunately the parallel execution still doesn't work as expected even at spec level. So far it is useless :( 

The execution of the tests is overriden in the same browser instance, so at least in this case it is only a partial fix. :(

**Comment by erdi** [comment]
There's [test coverage for supporting Spock's parallel execution](https://github.com/geb/geb/blob/92c0f481984333da7d5df7faecfad2867a6c66bc/module/geb-spock/src/test/groovy/geb/spock/ParallelExecutionSpec.groovy#L24) and that spec was failing prior to the fix I applied so I'm fairly certain that it works. I suspect there might be something in your setup, @DaniP13, causing it to not work as expected. Can you please share your `GebConfig.groovy`?

**Comment by DaniP13** [comment]
> There's [test coverage for supporting Spock's parallel execution](https://github.com/geb/geb/blob/92c0f481984333da7d5df7faecfad2867a6c66bc/module/geb-spock/src/test/groovy/geb/spock/ParallelExecutionSpec.groovy#L24) and that spec was failing prior to the fix I applied so I'm fairly certain that it works. I suspect there might be something in your setup, @DaniP13, causing it to not work as expected. Can you please share your `GebConfig.groovy`?

I've verified every single line and you were right, everithing was properly setup with only one exception:
**cacheDriverPerThread** which was missing. Once I added it and set it on _true_ the parallel execution worked as expected. 
Thank you very much for the effort, now we can finally use parallel execution !

Definitely this issue is verified as FIXED! 👍 💯 xThanks

**Comment by erdi** [comment]
Awesome, I'm glad that you figured out what additional changes were needed in your case and that it is now working for you, @DaniP13.
