### ISSUE TITLE
Problem with Geb interaction with Appium. 

### ISSUE THREAD

**Issue by dariusznalroche** [geb/issues#646]
I added the selector on page and on page it worked. I moved that selector to the module and it doesn't work. When trying to call this page object like this loaderMobileModule { module LoaderMobileModule } does not see this object and cannot be called. The issue is with the android appium selectors placed in the module. I get an error like this: 
![MicrosoftTeams-image](https://user-images.githubusercontent.com/77498696/134690515-9a944048-4f95-46ac-97fb-f334ff817d11.png)

**Comment by erdi** [comment]
Please do not post usage questions as issues. To get support please post to the [user mailing list](https://groups.google.com/g/geb-user). You will also need to post more information that just a partial (I assume it's partial cause there are no Geb classes in it) screenshot of the stacktrace if you want for people to be able to help you - namely the exact code of the test and page before you introduced the module and after you introduced it.
