### ISSUE TITLE
Getting below exception with gradle 6.8.3 version

### ISSUE THREAD

**Issue by stangatur-rgare** [geb/issues#651]
I am trying to implement geb cucumber for my project with gradle 6.8.3 and groovy 2.5.14 and geb 4.1 and using the setting from 
https://github.com/geb/geb-example-cucumber-jvm/blob/master/build.gradle

**Getting below exception, please hlep me fixing this issue:**

An exception occurred applying plugin request [id: 'com.github.samueltbrown.cucumber', version: '0.9']
> Failed to apply plugin 'com.github.samueltbrown.cucumber'.
   > Could not create an instance of type com.excella.gradle.cucumber.CucumberJvmOptions.
      > Could not find matching constructor for: org.gradle.process.internal.DefaultJavaForkOptions(org.gradle.api.internal.file.BaseDirFileResolver)

**Comment by stangatur-rgare** [comment]
Can someone please look into this issue?

**Comment by erdi** [comment]
This is a usage question and not a problem in Geb. As was already suggested when you opened this ticket, please do not post usage questions as issues and post them to [Geb's user mailing list](https://groups.google.com/g/geb-user) instead.
