### ISSUE TITLE
Firefox driver fails to initialize when running JAR

### ISSUE THREAD

**Issue by tcrespog** [geb/issues#652]
### Description

Hi. Apologies in advance if this turns out to be a question rather than an issue due to a misconfiguration on my side, but I'm experiencing an error that I'm not able to solve.

I have generated a fat JAR (using [Gradle Shadow](https://github.com/johnrengelman/shadow) plugin) to run some web scraping logic with Geb; however, when running it using Firefox, the driver fails to initialize. It doesn't seem to happen when running against Chrome or when using `./gradlew run`. In addition, I'm building with Java 8 (Corretto) in Windows 10.

In case it helps, I'm printing a line in the corresponding `GebConfig.groovy` environment, and I manage to see it duplicated before the error traces, which don't seem to provide much information:
```
$ java -jar geb-fat-jar.jar
Executing GebConfig
Executing Firefox environment closure <--------- duplicated line
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Executing Firefox environment closure <--------- duplicated line
Exception in thread "main" org.openqa.selenium.WebDriverException: Build info: version: '4.1.2', revision: '9a5a329c5a'
System info: host: 'laptop', ip: '192.168.1.38', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_322'
Driver info: driver.version: FirefoxDriver
        at java.util.Optional.orElseThrow(Optional.java:290)
        at org.openqa.selenium.firefox.FirefoxDriver.toExecutor(FirefoxDriver.java:174)
```

### Sample App

The sample app is available here: https://github.com/tcrespog/geb-fat-jar.

In order to reproduce the issue:
1. Run `./gradlew shadowJar`.
2. Go to the generated JAR located in `build/libs/geb-fat.jar`.
3. Run `java -jar geb-fat.jar`.

**Comment by erdi** [comment]
This is a usage questions, please post it on [the user mailing list](https://groups.google.com/g/geb-user)

**Comment by tcrespog** [comment]
For those who may stumble upon this issue, it got solved by applying the [`mergeServiceFiles()`](https://imperceptiblethoughts.com/shadow/configuration/merging/#merging-service-descriptor-files) config to `shadowJar`; without it, only the Chrome driver was present in the `META-INF/services/org.openqa.selenium.WebDriverInfo` file, so the Firefox driver wasn't being found.

Sorry for the noise.
