### ISSUE TITLE
Support Groovy 4

### ISSUE THREAD

**Issue by SchulteDev** [geb/issues#668]
Geb relies on Groovy 3 dependencies. Please make it possible to use Geb with Groovy 4, too.

**Actual problem**

When using Geb within a Groovy 4 project, there are clashing dependencies. I tried Geb:6.1-SNAPSHOT too (seems to be the same as 6.0 for time being).

org.apache.groovy:groovy-all:4.0.4 requires org.apache.groovy:groovy-templates:4.0.4, but org.gebish:geb-spock:6.0 requires org.codehaus.groovy:groovy-templates:3.0.12
```bash
Execution failed for task ':compileTestGroovy'.
> Could not resolve all files for configuration ':testCompileClasspath'.
   > Could not resolve org.apache.groovy:groovy-templates:4.0.4.
     Required by:
         project : > org.apache.groovy:groovy-all:4.0.4
         project : > org.apache.groovy:groovy-all:4.0.4 > org.apache.groovy:groovy:4.0.4 > org.apache.groovy:groovy-bom:4.0.4
      > Module 'org.apache.groovy:groovy-templates' has been rejected:
           Cannot select module with conflict on capability 'org.codehaus.groovy:groovy-templates:4.0.4' also provided by [org.codehaus.groovy:groovy-templates:3.0.12(compile)]
   > Could not resolve org.codehaus.groovy:groovy-templates.
     Required by:
         project : > org.gebish:geb-spock:6.0
         project : > org.gebish:geb-spock:6.0 > org.gebish:geb-core:6.0
         project : > org.gebish:geb-spock:6.0 > org.gebish:geb-core:6.0 > org.gebish:geb-ast:6.0
         project : > org.gebish:geb-spock:6.0 > org.gebish:geb-core:6.0 > org.gebish:geb-waiting:6.0
         project : > org.gebish:geb-spock:6.0 > org.gebish:geb-core:6.0 > org.gebish:geb-waiting:6.0 > org.gebish:geb-implicit-assertions:6.0
         project : > org.gebish:geb-spock:6.0 > org.gebish:geb-core:6.0 > org.gebish:geb-waiting:6.0 > org.gebish:geb-exceptions:6.0
      > Module 'org.codehaus.groovy:groovy-templates' has been rejected:
           Cannot select module with conflict on capability 'org.codehaus.groovy:groovy-templates:3.0.12' also provided by [org.apache.groovy:groovy-templates:4.0.4(groovyApiElements)]
   > Could not resolve org.codehaus.groovy:groovy-templates:3.0.12.
     Required by:
         project : > org.gebish:geb-spock:6.0 > org.codehaus.groovy:groovy-bom:3.0.12
      > Module 'org.codehaus.groovy:groovy-templates' has been rejected:
           Cannot select module with conflict on capability 'org.codehaus.groovy:groovy-templates:3.0.12' also provided by [org.apache.groovy:groovy-templates:4.0.4(groovyApiElements)]
```
This is from https://github.com/SchulteMarkus/spock-geb-demo/pull/25, I am providing a minimal Gradle/Groovy/Geb/Spock demo in this repository.

**Groovy4**

As far as I can see Geb relies on Groovy 3 aka org.codehaus.groovy, for example in https://github.com/geb/geb/blob/master/buildSrc/src/main/groovy/geb.groovy-3-module.gradle 
Groovy 4 was released in January 2022. Besides others, the [Maven coordinates changed](https://groovy-lang.org/releasenotes/groovy-4.0.html) from org.codehaus.groovy to org.apache.groovy

**Inspiration from Spock**
Spock is supporting Groovy since v2.2, see https://github.com/spockframework/spock/pull/1382

**Comment by erdi** [comment]
Hi @SchulteMarkus,

Thanks for asking for this, it's good to know that there is a need for it. 

The switch from Groovy 2.5 to Groovy 3 happened in Geb 5. I've just released Geb 6 which is still based on Groovy 3 but switches the Selenium version used from 3 to 4. I have limited resources (I'm the sole maintainer of the project with very little time at the moment) so I do not plan to release multiple versions of Geb supporting various combinations of Groovy, Spock and Selenium. Geb will switch from Groovy 3 to Groovy 4 from Spock 2.1 to 2.2 in the next major release. I would guess that this will happen in the next 3 to 6 months.
