### ISSUE TITLE
Geb 2.0+ No Tests Executed

### ISSUE THREAD

**Issue by tylercot** [geb/issues#669]
I'm not super familiar with Geb, but my app is currently running Grails 2.5.6 on Geb 1.0 with Selenium versions 3.141.59.

now, My BuildConfig
       
```
test group: 'org.gebish', name: 'geb-spock', version: '1.0'
test group: 'org.seleniumhq.selenium', name: 'selenium-support', version: '3.141.59'
test group: 'org.seleniumhq.selenium', name: 'selenium-chrome-driver', version: '3.141.59'
test group: 'org.seleniumhq.selenium', name: 'selenium-firefox-driver', version: '3.141.59'
test group: 'org.seleniumhq.selenium', name: 'selenium-ie-driver', version: '3.141.59'
```

running tests all I have to do is `grails test-app functional: org.geb.test.LoginFormSpec`

After updating geb-spock to 2.0 and Selenium to 3.6.0, running the same command doesn't execute any tests. Am I missing something here? I can't find anything to explain this.

**Comment by erdi** [comment]
This is not an issue but a usage question. Please ask usage questions on [the user mailing list](https://groups.google.com/forum/#!forum/geb-user) instead as suggested in the issue template.
