### ISSUE TITLE
getDevTools() is not available in Browser object

### ISSUE THREAD

**Issue by jain87varun** [geb/issues#672]
I am trying to use Network Interception in Selenium 4 for which I need to create DevTools object by invoking getDevTools() function through driver object `DevTools devTools = driver.getDevTools()`.
The above statement works in GebConfig.groovy file where driver is created but it is not available when I want to use it in the cucumber step implementation class through a browser object. I also tried to use it through `browser.driver.getDevTools()` but getDevTools() is not available in this way either.

**Comment by erdi** [comment]
If the driver instance you are using implements `org.openqa.selenium.devtools.HasDevTools`, which is where `getDevTools()` comes from, then simply cast `browser.driver` to that. If you are using remote web driver then you will need to [augment](https://www.selenium.dev/selenium/docs/api/java/org/openqa/selenium/remote/Augmenter.html#augment(org.openqa.selenium.WebDriver)) `browser.driver` first and then cast it to `HasDevTools`.  

Btw, `Browser.driverAs()` was introduced in 6.0. That method will first check if the driver is an instance of the passed type and if not then it will check if the augmented driver is an instance of the passed type. You can therefore use it like this to get an instance of `DevTools`:
```
def devTools = browser.driverAs(HasDevTools).get().devTools
```
