### ISSUE TITLE
Incorrect handling of skipped items in the OnFailureReporter

### ISSUE THREAD

**Issue by AlexeyAkentyev** [geb/issues#676]
I notice incorrect (or maybe inconsistent) behavior in the `OnFailureReporter` when the test (feature) is skipped.
The root cause of the issue s how Spock handles skips (https://github.com/spockframework/spock/blob/master/spock-core/src/main/java/org/spockframework/runtime/MasterRunSupervisor.java#L49):
```
ErrorInfo transformedError = new ErrorInfo(error.getMethod(), exception);
if (exception instanceof TestAbortedException || exception instanceof TestSkippedException) {
  // Spock has no concept of "aborted tests", so we don't notify Spock listeners
} else {
  masterListener.error(transformedError);
}
```

But in the current implementation of the [`OnFailureReporter`](https://github.com/geb/geb/blob/master/module/geb-spock/src/main/groovy/geb/spock/OnFailureReporter.groovy#L26) there is no such logic that leads to triggering failure logic for a skipped test (feature). It's quite painful in some cases.
E.g. I'm using quite a lot `Assumptions.assumeTrue()` in tests because of the application specific and each skipped item triggering failure logic (taking screenshots and other time-consuming operations)

@erdi could you share your opinion about the issue? I propose adding an extra logic that will replicate Spock's behavior (feel free to advise a better solution).
I'm ready to contribute and create PR.

**Comment by erdi** [comment]
I agree that reports should not be written for skipped/aborted tests when `reportOnTestFailureOnly` is set to `true`. This is clearly an omission in the implementation.

Thanks for reporting and providing a PR with a fix, @AlexeyAkentyev. I will pull it and apply some tweaks afterwards as that will be the most efficient way of dealing with it.
