### ISSUE TITLE
Willing to hand the project over?

### ISSUE THREAD

**Issue by Poundex** [geb/issues#692]
Hi @erdi ,

I saw your announcement on the main Geb repo about how you no longer have the bandwidth available to maintain the project. I think it would be such a shame to see this project disappear so I am thinking about forking it and trying to keep it going. 

I was wondering if you would be willing to hand the project over? Allowing the fork to keep the name Geb, allowing me to buy the domain from you, and allowing me to take over the Maven Central account? Plus anything else I haven't thought about

**Comment by erdi** [comment]
I think it would be easier for me to hand it over to somebody I've had a chance to collaborate with in the past or somebody who contributed to the project but I doubt anybody like that will come forward so we might as well do it.

Are you sure you want to do it? What's your motivation? Just handing it over will be a lot of work on my end so I'd rather it did not go to waste. Things that we would need to give you admin access to/hand are at least the following but there might be more:
- github org
- domain
- name servers config
- ability to publish to the org in maven central
- ability to publish the website at heroku
- CI in circle and appveyor
- accounts at BrowserStack, Sauce Labs and LambdaTest
- mailing lists

**Comment by Poundex** [comment]
Yes I am absolutely determined that this project lives on, I believe for Geb to go away would be a great loss. I fully appreciate that time and effort costs on a project you were trying to step away from, however Geb is quite a mature project and I think that abandoning all the work that has gone into it from all its contributors over more than a decade would be the greater waste. All I can do is promise that I would provide any help I could to make things as painless as possible on your end.

I also fully understand why you'd rather hand the project over to someone who was already actively contributing to the project, or you knew personally, and I don't know if any search efforts to find someone like this are ongoing, but the EOL notices are already live on the repo and the website (and being noticed: https://github.com/spockframework/spock/discussions/1993 ) and so that's why I decided to reach out.

**Comment by blackdrag** [comment]
There is also the possibility to come to the Apache Foundation maybe as another top level project, maybe as a sub project with a later graduation to top level. It depends on how much of an active community there is. If not so many I would go with a sub project and if you find a lot of motivated people to continue in Apache, then as top level project. Of course if suddenly a lot of motivated people show up anyway, then there is no strict need to go to Apache. But at least mailing lists, domains, the github and releasing would be clear. Even though a lot of things would change. BrowserStack, Sauce Labs and LambdaTest as well as Appveyor is not so clear though.

**Comment by sbglasius** [comment]
@erdi While @Poundex's offer is nice, I agree with @blackdrag that it should be cleared if the ASF could see it as a project under their umbrella. @Poundex could, if she/he wants be a part of the Project Management Committee (PMC).
I do not currently have cycles left to spare running in that direction, so just my €0.05 worth.

**Comment by sbglasius** [comment]
I have pinged @paulk-asert on the Groovy Slack and he is positive too, writing:

> I would be keen to consider bringing Geb into ASF as a subproject for Groovy but we'd probably need a few (existing or new) committers willing to help out with fixes and releases.

**Comment by erdi** [comment]
To set the expectations straight, while I'm more than happy to hand the keys to the project over I have no capacity whatsoever to get involved in any process required to bring the project under the ASF umbrella so that would need to be a community led effort.

To be frank, I'm at the point where I think that if somebody truly cares about the project then they can always fork. There's never been anybody who would significantly contribute to the project other than Luke Daley and myself and I doubt that out of a sudden active contributors with enough steam in them to deal with fixes and releases would appear.

**Comment by blackdrag** [comment]
@Poundex would you contribute to GEB if it was a subproject of Apache Groovy? Because if the community is not big enough for an active project on its own in ASF, then this would be the way to go - unless somebody takes over independently.

**Comment by sdelamo** [comment]
+1 for Geb moving to ASF a a subproject of Apache Groovy.

**Comment by jonnybot0** [comment]
So, we've been following this exchange and [the notes in the Groovy Community Slack](https://groovy-community.slack.com/archives/C2NEFCM55/p1725357891168099). It seems like there's general enthusiasm about bringing it under the Apache Software Foundation umbrella, and even some folks who would like to contribute.

My team still relies on Geb for testing some of our flagship products, and would be willing to assume some maintenance responsibility.

So I guess I'm putting myself forward to:
1. Handle assuming management of transfer of all of [the resources Marcin laid out in his comment](https://github.com/geb/issues/issues/692#issuecomment-2313488649) to a community management of some kind.
2. Start the process of bringing Geb under ASF stewardship, with the support of the rest of the community
3. Do some routine maintenance for the near term.

To be clear, if someone else has already stepped forward, that is more than fine. My goal is to take the good will that seems to already be out there and move it forward so it doesn't stall out.

**Comment by erdi** [comment]
Thanks for stepping up, @jonnybot0. I'm happy to hand over the keys to you because I know you personally and I know that you will have motivation to maintain the project because it's being used by your employer.

Please let me know how you would like to progress.

**Comment by jonnybot0** [comment]
As an update to everyone, I met with @erdi last week to start handing over the GitHub project & other key assets. Work is still ongoing, and I'm working with Paul King and the Groovy project leads to move Geb under the ASF umbrella.

I'd like to talk to @Poundex, @sdelamo, & @sbglasius if you are interested in contributing. There is some maintenance work that needs done on Geb. Having some additional contributors and plans for regular maintenance would be good. You can find me in the Groovy community Slack or email me at jcarter [at] adaptavist.com.

**Comment by Poundex** [comment]
Sorry about the delayed response but I am still happy to contribute what I can. I've spoken to @jonnybot0 via e-mail and got myself an account in the Groovy Slack.

**Comment by jonnybot0** [comment]
As should be clear to anyone following this issue, or happening upon it, Geb is now in good hands! We've updated [the site](https://gebish.org/) to remove the "end of maintenance" banner. Work is ongoing by @sdelamo, @Poundex, and myself to do the maintenance needed to keep Geb maintained. 

Work is also underway to move Geb under Groovy's ASF umbrella. There are still some hurdles to clear, but for now, rest assured that Geb is in good hands.
